### ISSUE TITLE
Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['entity_id']

### ISSUE THREAD

**Issue by pr0fetul** [fondberg/spotcast#107]
Hi, first of all - awesome work!!!! Kudos !!!
HA  0.111.4 in Docker
Second :( I have an issue which I cannot understand (it may be a minor slip) - after installing from HACS the spotcast, configuring it with the cookies, from Service - Call Service with the below code it works without an issue - the music starts immediately.
code 1 which works:
`**Service:**
spotcast.start
**Entity:**
media_player.office_speaker
**Service Data (YAML, optional):**
device_name: Office speaker
entity_id: media_player.office_speaker
uri: 'spotify:playlist:37i9dQZF1DX7cZxYLqLUJl'
random_song: true
shuffle: true
device_name: Office speaker
entity_id: media_player.office_speaker
uri: 'spotify:playlist:37i9dQZF1DX7cZxYLqLUJl'
random_song: true
shuffle: true​
`
If I put the same as above in a script - Morning Alarm - it does not work anymore and throws the error in the subject
code 2 which does not work:
Script:
`
'1593159898420':
  alias: Morning Alarm
  sequence:
  - data:
      random_song: true
      shuffle: true
      uri: spotify:playlist:37i9dQZF1DX7cZxYLqLUJl
    entity_id: media_player.office_speaker
    service: spotcast.start
`
The error code is:

`
2020-06-26 11:31:06 INFO (MainThread) [homeassistant.components.script] Morning Alarm: Running script
2020-06-26 11:31:06 INFO (MainThread) [homeassistant.components.script] Morning Alarm: Executing step call service
2020-06-26 11:31:06 ERROR (MainThread) [homeassistant.components.script] Morning Alarm: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['entity_id']
2020-06-26 11:31:06 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140331804021776] value should be a string for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 207, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 284, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 831, in async_run
    await run.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 555, in async_run
    await self._async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 572, in _async_run
    await self._async_step(log_exceptions=not propagate_exceptions)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1222, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value should be a string for dictionary value @ data['entity_id']
`
Any ideas on what I am missing? Thank you very much.

**Comment by notpurum** [comment]
Make sure you use the correct indentation. Your code should look like this:
```
morning_alarm:
  alias: Morning Alarm
  sequence:
    random_song: true
    shuffle: true
    uri: spotify:playlist:37i9dQZF1DX7cZxYLqLUJl
    entity_id: media_player.office_speaker
    service: spotcast.start
```

**Comment by pr0fetul** [comment]
@notpurum 
if I use this setup you mentioned, I cannot save and reload the script as it throws an error about formatting

```
'1593159898420':
  alias: Morning Alarm
  sequence:
    - service: spotcast.start
      random_song: true
      shuffle: true
      uri: spotify:playlist:37i9dQZF1DX7cZxYLqLUJl
      entity_id: media_player.office_speaker
```

error:

`Invalid config for [script]: [random_song] is an invalid option for [script]. Check: script->script->1593159898420->sequence->0->random_song. (See /config/configuration.yaml, line 17). `

It seems it does not like attributes under -service

**Comment by fondberg** [comment]
Please use the forum for support questions on HA related things
