### ISSUE TITLE
ERROR: exceeded 30 redirects

### ISSUE THREAD

**Issue by davidrustingha** [fondberg/spotcast#108]
When trying to fire Spotcast within a script or within the service menu in HA I get this error.

Script or service call: 
```
    - service: spotcast.start
      data:
        uri: 'spotify:track:7CpbhqKUedOIrcvc94p60Y'
        device_name: HOME-ASSISTANT
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1299, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 199, in start_casting
    access_token, expires = get_token_instance(account).get_spotify_token()
  File "/config/custom_components/spotcast/__init__.py", line 262, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(self.sp_dc, self.sp_key)
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 19, in start_session
    headers=headers, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

Spotcast does work within the Spotify playlist card

**Comment by fondberg** [comment]
The card uses another endpoint than the component for spotify auth. What you saw means that thr browser auth service was down for you at that time

**Comment by davidrustingha** [comment]
Do you have an idea what I can do about it?

**Comment by fondberg** [comment]
Seems others have problems with using a script so i would ask in the forum seeing as it works in the card.
What you probably need is to add debug logs.
