### ISSUE TITLE
 'Spotify' object has no attribute 'playlist_tracks'

### ISSUE THREAD

**Issue by andysmithfal** [fondberg/spotcast#112]
Just upgraded to the latest version of HA and spotcast (via HACS). I'm getting the following error when triggering a script that casts a playlist:

```
Start Spotify (Bedroom): Error executing script. Unexpected error for call_service at pos 1: 'Spotify' object has no attribute 'playlist_tracks'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1299, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 242, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 172, in play
    results = client.playlist_tracks(uri)
AttributeError: 'Spotify' object has no attribute 'playlist_tracks'
```

This is my script: 

```
start_spotify_bedroom:
  alias: Start Spotify (Bedroom)
  sequence:
    - service: spotcast.start
      data:
        entity_id: media_player.bedroom_speaker
        uri: spotify:playlist:6tlRHSvzXGvmOwLgV2XMHj
        random_song: true
```

The extension does seem to work otherwise, if I omit the URI and use force_playback it will resume playing fine. Specifying a single track URI also works fine. 

Thanks

**Comment by fondberg** [comment]
Which version of HA? I think there are some updated libraries that needs bumping here

**Comment by andysmithfal** [comment]
112.3

**Comment by andysmithfal** [comment]
Still experiencing this issue on 3.2.4, not sure if that should have fixed it?

**Comment by fondberg** [comment]
It works for me. Can you send all logs with debug enabled for spotcast?

**Comment by andysmithfal** [comment]
Confirming this now works for me again in HA 112.4 and Spotcast 3.3.0
