### ISSUE TITLE
0.113.0 AttributeError

### ISSUE THREAD

**Issue by Spankythemusical** [fondberg/spotcast#114]
Upgraded Home Assistant to 0.113.0, (Spotcase v. 3.3.4) and now my log is filled with the following error:

`2020-07-23 15:09:57 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chromecast_devices fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 465, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/spotcast/sensor.py", line 54, in update
    'name': cast.name,
AttributeError: 'list' object has no attribute 'name'`

This error is repeated around every 60 seconds, so my log size quickly increases.

**Comment by fondberg** [comment]
Please turn on debug for spotcast and send relevant spotcast log lines

**Comment by fondberg** [comment]
Fixed in 3.3.5 https://github.com/fondberg/spotcast/releases/tag/v3.3.5
