### ISSUE TITLE
Timeout when waiting for status response from Spotify app

### ISSUE THREAD

**Issue by joshtbernstein** [fondberg/spotcast#117]
When clicking on a playlist, I hear the chime from my Google Home, but the music never starts playing. My Spotify app seems to be configured correctly as it does show what's playing on my Spotify app (phone, computer, etc).

HA gives the following error:

Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.139999491359360
Source: custom_components/spotcast/__init__.py:449
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:19:21 PM (4 occurrences)
Last logged: 1:20:10 PM

Timeout when waiting for status response from Spotify app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1320, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 300, in start_casting
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/__init__.py", line 449, in startSpotifyController
    sp.launch_app()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/spotify.py", line 84, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app

**Comment by fondberg** [comment]
Which spotcast version and HA version are you using?

**Comment by joshtbernstein** [comment]
Oops! Sorry.
HA: 0.113.2
Spotcast: 3.4.0

**Comment by fondberg** [comment]
Is this still happening?

**Comment by fondberg** [comment]
Closing due to lack of information
