### ISSUE TITLE
Update for sensor.chromecast_devices fails

### ISSUE THREAD

**Issue by PSJMcNeill** [fondberg/spotcast#119]
Just installed via HACs yesterday.

HACs version:
    Integration version: 1.3.0b1
    Frontend version: 202017310251

Added spotcast with sp_dc and sp_key to configuration.yaml.

I then tried using the spotify_custom_card but Chromecast Devices never show up.

Checking the logs I can see this:

Logger: homeassistant.helpers.entity
Source: custom_components/spotcast/sensor.py:61
First occurred: 11:31:25 (33 occurrences)
Last logged: 11:37:15

Update for sensor.chromecast_devices fails

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 61, in update
    for k in known_devices
  File "/config/custom_components/spotcast/sensor.py", line 61, in <listcomp>
    for k in known_devices
TypeError: 'set' object is not subscriptable`

**Comment by fondberg** [comment]
You need HA v 0.113 or newer
