### ISSUE TITLE
Failed to call service spotcast/start. Could not get spotify token

### ISSUE THREAD

**Issue by cben0ist** [fondberg/spotcast#121]
Hi,

I've had that issue for a long time and I thought my configuration was wrong until I got everything working perfectly 2 days ago but today the same issue came back again without any changes on my installation.
Are these due to problems/limitations on Spotify ?

- v3.4.1 on 0.113.3
- Players are working well when spotify. is launched (from my phone for example)
- Spotify Lovelace Card is empty
- this error triggers when I manually call the spotcast.start service with entity_id and uri

Thanks

```
Traceback (most recent call last):
  File "/config/custom_components/spotcast/__init__.py", line 365, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(self.sp_dc, self.sp_key)
  File "/usr/local/lib/python3.8/site-packages/spotify_token.py", line 18, in start_session
    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1320, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 286, in start_casting
    access_token, expires = get_token_instance(account).get_spotify_token()
  File "/config/custom_components/spotcast/__init__.py", line 369, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token
```

**Comment by cben0ist** [comment]
OK... My sp_dc and sp_key had changed overnight...
