### ISSUE TITLE
Cant start playback on chromecast-audio

### ISSUE THREAD

**Issue by discodogge** [fondberg/spotcast#129]
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:313
First occurred: 15:06:35 (7 occurrences)
Last logged: 15:34:25

Uncaught thread exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 526, in run
    self.initialize_connection()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 359, in initialize_connection
    self.socket.connect((self.host, self.port))
TypeError: str, bytes or bytearray expected, not NoneType

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.3
supervisor | 245
timezone | Europe/Stockholm
version | 0.114.4
virtualenv | false

it has been iffy for a while. but now lately have not been working at all. I have removed the plugin and try reinstalling but it remains notable. 
really like the project. and will try to contribute whit whatever I can but I'm really a noob when it comes to programming.

**Comment by discodogge** [comment]
never mind I think the problem seems to be that I hade a faulty power supply on one Chromecast. sorry to bother you
//Danne
