### ISSUE TITLE
Timeout when waiting for status response from Spotify app - NodeRed Only

### ISSUE THREAD

**Issue by radiohe4d** [fondberg/spotcast#140]
Hi, just installed Spotcast through HACS for the first time and in Developer Tools managed to run the following successfully:

```
service: spotcast.start
entity_id: media_player.kitchen_speaker
uri: 'spotify:album:6JdX9MGiEMypqYLMKyIE8a'
force_playback: true
```

But when i create a 'call-service' node in NodeRed and try to call it with the same settings as above, it fails with the following error:

`Call-service API error.  Error Message: Timeout when waiting for status response from Spotify app` 

Any idea what might cause this to happen/how to resolve this?

Thanks :)

### Versions:
```
SpotCast: v3.4.4
HassOS: 4.15
Supervisor: 2020.11.0
HomeAssistant: 0.117.5
NodeRed: 7.2.8
node-red-contrib-home-assistant-websocket: 0.27.4
```

### Supervisor Logs:
```
20-11-08 21:36:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
20-11-08 21:36:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
20-11-08 21:36:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-11-08 21:36:17 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
20-11-08 21:36:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

### Core Logs:
```
2020-11-08 21:36:22 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2792949792] Timeout when waiting for status response from Spotify app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1487, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 292, in start_casting
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/__init__.py", line 452, in startSpotifyController
    sp.launch_app()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/spotify.py", line 88, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```

### NodeRed Logs:
```
[08/Nov/2020:21:33:18 +0000] 200 95.145.196.232, 172.30.32.1(172.30.32.2) GET /red/images/typedInput/json.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36)
[08/Nov/2020:21:33:18 +0000] 200 95.145.196.232, 172.30.32.1(172.30.32.2) GET /red/images/typedInput/expr.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36)
[08/Nov/2020:21:33:30 +0000] 200 95.145.196.232, 172.30.32.1(172.30.32.2) GET /vendor/ace/worker-json.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36)
8 Nov 21:36:12 - [info] Stopping flows
8 Nov 21:36:12 - [info] [server:Home Assistant] Closing connection to http://supervisor/core
8 Nov 21:36:12 - [info] [mqtt-broker:MQTT] Disconnected from broker: node-red@mqtt://localhost:1883
8 Nov 21:36:12 - [info] Stopped flows
8 Nov 21:36:12 - [info] Starting flows
8 Nov 21:36:13 - [info] [sun events:35196664.621fea] Calculating sun event times for 52.353861, -1.518722.
8 Nov 21:36:13 - [info] Started flows
[08/Nov/2020:21:36:13 +0000] 200 95.145.196.232, 172.30.32.1(172.30.32.2) POST /flows HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36)
8 Nov 21:36:13 - [info] [mqtt-broker:MQTT] Connected to broker: node-red@mqtt://localhost:1883
8 Nov 21:36:17 - [info] [server:Home Assistant] Connecting to http://supervisor/core
8 Nov 21:36:17 - [info] [server:Home Assistant] Connected to http://supervisor/core
8 Nov 21:36:22 - [error] [api-call-service:Spotcast] Call-service API error.  Error Message: Timeout when waiting for status response from Spotify app
8 Nov 21:36:22 - [error] [api-call-service:Spotcast] Call-service API error.  Error Message: Timeout when waiting for status response from Spotify app
```

**Comment by gmcmicken** [comment]
I had the same problem, with a different tigger. Turns out I was calling the service twice so check and be sure it's only being called once.

**Comment by radiohe4d** [comment]
Installed the latest v3.4.5 and now its working perfectly! 

Also updated other areas too:
```
HassOS: 4.17
HomeAssistant: 0.118.0
NodeRed (HA): 7.2.10
NodeRed: 1.2.5
```

I suspect the first time i installed it, it didn't go so well, and a re-install may have solved this. 

Thanks for your reply @gmcmicken , although it wasn't an issue for me, i have had this be a problem in the past.
