### ISSUE TITLE
http status: 403

### ISSUE THREAD

**Issue by TheWorstAvenger** [fondberg/spotcast#148]
Im not able to start spotify on a google home mini with DuckDNS enabled. When I start spotify per voice, I'm able to controll it but I'm not able to start in homeassistant. Before I used the DNS it was working fine, but now I'm getting http status: 403

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:259
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:14:02 (2 occurrences)
Last logged: 10:16:42

[547803210608] http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=7621608115f1a529c9e90567f94a0c3e: Player command failed: Restriction violated, reason: UNKNOWN
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/player/play?device_id=7621608115f1a529c9e90567f94a0c3e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 307, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 259, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 1706, in start_playback
    return self._put(
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 306, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=7621608115f1a529c9e90567f94a0c3e:
 Player command failed: Restriction violated, reason: UNKNOWN
```

**Comment by strandaster** [comment]
Did you already enabled the debug logging for spotcast? This was helping me a lot to get information what was requested from the API of Spotify.

**Comment by AdrinkBeer** [comment]
I have the same issue.

@strandaster Can you please tell me how to enable debug logging ? Thanks!

**Comment by strandaster** [comment]
> @strandaster Can you please tell me how to enable debug logging ? Thanks!

Add in your configuration.yaml following paragraph:

logger:
  default: error
  logs:
    custom_components.spotcast: debug

**Comment by fondberg** [comment]
Closing this because lack of info
