### ISSUE TITLE
None of my Spotify Connect devices show up

### ISSUE THREAD

**Issue by gabosom** [fondberg/spotcast#167]
First of all, thanks for creating this integration, I can't wait to use it!   The issue I'm having is that none my spotify connect devices are showing up in the sensor - the only device I really care about is my receiver "Pioneer" in the screenshot below.  

Thoughts on next steps to troubleshoot?

![image](https://user-images.githubusercontent.com/926425/108634886-bcd10800-7430-11eb-8cf4-d3dfb13ba955.png)

![image](https://user-images.githubusercontent.com/926425/108634919-002b7680-7431-11eb-8879-d82563d96f44.png)

**Comment by gabosom** [comment]
This is what I tried to run in the developer tools
`device_name: Receiver
uri: 'spotify:playlist:5tEosAM9zwoygzM5oF8L5z'
random_song: true`


I see two entries in the logs
`Logger: custom_components.spotcast
Source: custom_components/spotcast/__init__.py:446
Integration: Start Spotify on chromecast (documentation)
First occurred: 10:49:47 AM (2 occurrences)
Last logged: 10:49:47 AM

Could not find device Receiver from hass.data`

and

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:451
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:49:47 AM (2 occurrences)
Last logged: 10:49:47 AM

[548081869152] Could not find device with name Receiver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1494, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 292, in start_casting
    spotify_cast_device = SpotifyCastDevice(
  File "/config/custom_components/spotcast/__init__.py", line 409, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 451, in getChromecastDevice
    raise HomeAssistantError("Could not find device with name {}".format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Receiver`

**Comment by gabosom** [comment]
Got it to work. rebooted HA and then used the device name _exactly as it shows up in Spotify_. Works like a charm, thx!
