### ISSUE TITLE
Can't play on device - 502 error

### ISSUE THREAD

**Issue by xmow49** [fondberg/spotcast#171]
Hi,
I use Spotcast since 1 year, but 1 week ago, my script stop working: I have an error: Device Name not found.
So, I had test the spotify api, to get my device id and update my script.
Its work, but if the spotify player stop after 10 min, no devices is selected, and the script dont work, and I have this:
```
2021-03-31 21:40:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140303295056912] http status: 429, code:-1 - /v1/me/player/play?device_id=22dec55512f7fd1773bf206bef1fcadf26******:
 Max Retries, reason: too many 502 error responses
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/player/play?device_id=22dec55512f7fd1773bf206bef1fcadf26******* (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 240, in _internal_call
    response = self._session.request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/player/play?device_id=22dec55512f7fd1773bf206bef1fcadf26******* (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 218, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 323, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1041, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 262, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 307, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 259, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 1706, in start_playback
    return self._put(
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 306, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 275, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/me/player/play?device_id=22dec55512f7fd1773bf206bef1fcadf26*******:
 Max Retries, reason: too many 502 error responses
```

_I had hide my id with ******_

If I select my device in spotify app, and I execute the script, its work.
So, it should Spotcast select the device before playing music.

Anyone have this problem?

Can you help me pls.

Thanks

**Comment by Bhgp-git** [comment]
https://github.com/fondberg/spotcast/issues/170 They have a solution here

**Comment by fondberg** [comment]
Fixed together with core PRs. Help me upvote them (links in this PR) https://github.com/fondberg/spotcast/pull/176

**Comment by fondberg** [comment]
Fixed in https://github.com/fondberg/spotcast/releases/tag/v3.5.2. Help me test that release.
