### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kordys** [fondberg/spotcast#185]
I use the spotcast in my automation to start the music like this:

` action:
    - service: spotcast.start
      data:
        device_name: 'Hostroom speaker'
        uri: "spotify:playlist:{{ ['...', '...', '...'] | random }}"
        force_playback: true
        shuffle: true
        random_song: true`

This worked like a charm for some time but broke recently. When I run the automation there is a log in the HA:

`2021-04-13 07:33:20 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:1df5d92d5308fb0692153c26f89dda2f): device_name=Hostroom speaker, force_playback=True, offset=0, start_volume=101, repeat=off, random_song=False, shuffle=False>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable`

I configured the spotcast sensor to get the list of devices and the Hostroom speaker is listed here among other devices so I believe the devices are discovered correctly.
`    {
        "host": "deprecated",
        "port": "deprecated",
        "uuid": "3e3ec751-e9b3-4cfe-ad28-f26b53aa3730",
        "model_name": "Google Home Mini",
        "name": "Hostroom speaker",
        "manufacturer": "Google Inc."
    },`

Is there anything I should check to find the cause of the issue?

Thanks a lot!

**Comment by adrienvsj** [comment]
Hello, I have the same error with last version of home assistant (2021.4.4) and last version of spotcast (v3.5.2)

When I try to use the service in development tools : 
`service: spotcast.start
data:
  entity_id: media_player.nest_hub
  uri: 'spotify:playlist:37i9dQZF1DX9ND1QF5hZNF'
  random_song: true
  shuffle: true
`

I got 2 errors in logs : 
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable`

and : 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable`

Thanks a lot for your work !

**Comment by mcfly2283** [comment]
Just install or reinstall the Spotify-Integration as mentioned in #182 https://github.com/fondberg/spotcast/issues/182

**Comment by kordys** [comment]
> Just install or reinstall the Spotify-Integration as mentioned in #182

Thanks! I missed that one. I will give it a try. I didn't realize I need the Spotify integration from now on...

**Comment by fondberg** [comment]
I updated the README about this
