### ISSUE TITLE
Error setting up in HA 2021.4.4

### ISSUE THREAD

**Issue by ColinRobbins** [fondberg/spotcast#191]
I'm still struggling with issue [174](https://github.com/fondberg/spotcast/issues/174), so I removed the Spotify and spotcast config, and upgraded to HA 2021.4.4

When adding the Spotify integration back, the call-back URL is called, but HA reports
```
500 Internal Server Error
```
I see in the logs:
```
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 71, in forwarded_middleware
return await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 74, in ban_middleware
return await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 135, in auth_middleware
return await handler(request)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 131, in handle
result = await result
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 146, in get
return await super().get(request, flow_id)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 93, in get
result = await self._flow_mgr.async_configure(flow_id)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 156, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
result: dict = await getattr(flow, method)(user_input)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 307, in async_step_creation
return await self.async_oauth_create_entry(
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/spotify/config_flow.py", line 43, in async_oauth_create_entry
spotify = Spotify(auth=data["token"]["access_token"])
File "/srv/homeassistant/lib/python3.9/site-packages/spotipy/client.py", line 166, in __init__
self._build_session()
File "/srv/homeassistant/lib/python3.9/site-packages/spotipy/client.py", line 193, in _build_session
retry = urllib3.Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```
I've triple checked the callback URL, and client ID / secret.

Any suggestions what the ```allowed_methods``` issue is?

**Comment by hmmbob** [comment]
This looks to me as a problem with the core `spotify` integration? This is the `spotcast` repository, you might have better luck at the Home Assistant Core repo?

**Comment by ColinRobbins** [comment]
Thanks @hmmbob, raised in the [HA Community](https://community.home-assistant.io/t/error-setting-up-spotify-in-ha-2021-4-4/299433) and closed here.
