### ISSUE TITLE
version 3.5.7 dont play music

### ISSUE THREAD

**Issue by michaeltryl** [fondberg/spotcast#208]
Have tried both with and without the dirty bug fix which has worked before, but the music does not start
i have this in my log.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 394, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(
  File "/config/custom_components/spotcast/__init__.py", line 582, in getSpotifyDeviceId
    if devices := devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by hmmbob** [comment]
What HA version are you running?
Do you have core Spotify setup?
Can you share your Spotcast config?

**Comment by michaeltryl** [comment]
i run HA version core-2021.4.6
i have the real spotify integration setup
and my config to spotcast is 

spotcast:
  sp_dc: xxxxxxxxxxxxxxxxxxxxxxxxxx
  sp_key: xxxxxxxxxxxxxxxxxxxxxxxxxx
  accounts:
    tobias:
      sp_dc: xxxxxxxxxxxxxxxxxxxxxxxxxx
      sp_key: xxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by bnutz** [comment]
> TypeError: 'NoneType' object is not subscriptable

Seeing the same error on my system as well.

Running core-2021.5.1 Docker Container version.

Tried removing and re-adding the core Spotify setup (restarting after each step) but still got the same error when attempting to play. 
I am using the `entity_id` as the target device to play on.

Also confirm the target devices are visible via the `sensor.chromecast_devices` sensor.

Currently rolled back to 3.5.6 and locally applied the dirty fix from this PR and everything is working again:
https://github.com/fondberg/spotcast/pull/202/files

**Comment by bnutz** [comment]
Updated to 3.5.8, and set to use `device_name`, but no change in results.

debug log output with some sanitisation and duplicate lines removed:
```
2021-05-10 18:02:11 DEBUG (SyncWorker_2) [custom_components.spotcast.sensor] initiating sensor
2021-05-10 18:02:26 DEBUG (SyncWorker_7) [custom_components.spotcast.sensor] Getting chromecast devices
2021-05-10 18:02:26 DEBUG (SyncWorker_7) [custom_components.spotcast] get_cast_devices: media_player.chromecast_audio_speaker: Chromecast Audio speaker cast info: ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.128', 8009)), ServiceInfo(type='mdns', data='Chromecast-Audio-123456781234123412341234567890ab._googlecast._tcp.local.')}, uuid='12345678-1234-1234-1234-1234567890ab', _manufacturer='Google Inc.', model_name='Chromecast Audio', friendly_name='Chromecast Audio speaker', is_audio_group=False, is_dynamic_group=None)
2021-05-10 18:02:26 DEBUG (SyncWorker_7) [custom_components.spotcast] get_cast_devices: media_player.mum_cast: Mum Cast cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-abcdefghabcdabcdabcdabcdefghijkl._googlecast._tcp.local.'), ServiceInfo(type='host', data=('###.###.###.61', 8009))}, uuid='abcdefgh-abcd-abcd-abcd-abcdefghijkl', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Mum Cast', is_audio_group=False, is_dynamic_group=None)
2021-05-10 18:02:26 DEBUG (SyncWorker_7) [custom_components.spotcast] get_cast_devices: media_player.chromecast_left: Chromecast Left cast info: ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.148', 8009)), ServiceInfo(type='mdns', data='Chromecast-876543214321432143210987654321ba._googlecast._tcp.local.')}, uuid='87654321-4321-4321-4321-0987654321ba', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Chromecast Left', is_audio_group=False, is_dynamic_group=None)
2021-05-10 18:02:26 DEBUG (SyncWorker_7) [custom_components.spotcast.sensor] sensor devices [ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.128', 8009)), ServiceInfo(type='mdns', data='Chromecast-Audio-123456781234123412341234567890ab._googlecast._tcp.local.')}, uuid='12345678-1234-1234-1234-1234567890ab', _manufacturer='Google Inc.', model_name='Chromecast Audio', friendly_name='Chromecast Audio speaker', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-abcdefghabcdabcdabcdabcdefghijkl._googlecast._tcp.local.'), ServiceInfo(type='host', data=('###.###.###.61', 8009))}, uuid='abcdefgh-abcd-abcd-abcd-abcdefghijkl', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Mum Cast', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.148', 8009)), ServiceInfo(type='mdns', data='Chromecast-876543214321432143210987654321ba._googlecast._tcp.local.')}, uuid='87654321-4321-4321-4321-0987654321ba', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Chromecast Left', is_audio_group=False, is_dynamic_group=None)]
2021-05-10 18:02:52 DEBUG (SyncWorker_9) [custom_components.spotcast] setting up with  account maggie
2021-05-10 18:02:52 DEBUG (SyncWorker_9) [custom_components.spotcast] Chromecast devices: [ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.128', 8009)), ServiceInfo(type='mdns', data='Chromecast-Audio-123456781234123412341234567890ab._googlecast._tcp.local.')}, uuid='12345678-1234-1234-1234-1234567890ab', _manufacturer='Google Inc.', model_name='Chromecast Audio', friendly_name='Chromecast Audio speaker', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-abcdefghabcdabcdabcdabcdefghijkl._googlecast._tcp.local.'), ServiceInfo(type='host', data=('###.###.###.61', 8009))}, uuid='abcdefgh-abcd-abcd-abcd-abcdefghijkl', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Mum Cast', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.148', 8009)), ServiceInfo(type='mdns', data='Chromecast-876543214321432143210987654321ba._googlecast._tcp.local.')}, uuid='87654321-4321-4321-4321-0987654321ba', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Chromecast Left', is_audio_group=False, is_dynamic_group=None)]
2021-05-10 18:02:52 DEBUG (SyncWorker_9) [custom_components.spotcast] cast info: ChromecastInfo(services={ServiceInfo(type='host', data=('###.###.###.128', 8009)), ServiceInfo(type='mdns', data='Chromecast-Audio-123456781234123412341234567890ab._googlecast._tcp.local.')}, uuid='12345678-1234-1234-1234-1234567890ab', _manufacturer='Google Inc.', model_name='Chromecast Audio', friendly_name='Chromecast Audio speaker', is_audio_group=False, is_dynamic_group=None)
2021-05-10 18:02:52 DEBUG (SyncWorker_9) [custom_components.spotcast] Found cast device: Chromecast(None, port=8009, device=DeviceStatus(friendly_name='Chromecast Audio speaker', model_name='Chromecast Audio', manufacturer='Google Inc.', uuid='12345678-1234-1234-1234-1234567890ab', cast_type='audio'))
2021-05-10 18:02:53 DEBUG (SyncWorker_9) [custom_components.spotcast] devices_available: None 47c9315e9e6c80fdc1c419fba4ecbd25
```

This is the error trace from the script that is calling the service:
```
2021-05-10 18:02:53 ERROR (MainThread) [homeassistant.components.script.spotify_baby_sleep] Sleep Baby Sleep: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 563, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1520, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 399, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(
  File "/config/custom_components/spotcast/__init__.py", line 587, in getSpotifyDeviceId
    if devices := devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
2021-05-10 18:02:53 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 404, in _async_run
    return await self.script.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1209, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 345, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 563, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1520, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 399, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(
  File "/config/custom_components/spotcast/__init__.py", line 587, in getSpotifyDeviceId
    if devices := devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
```


An additional observation - this is only affecting playlists being played from the secondary account(s). 
When not using the `account` param - using `device_name` or `entity_id` with the default account is able to work without issue.

**Comment by JOHLC** [comment]
I am only using one account with Spotcast and I have been getting a similar error and an inability to play anything:

```
Log Details (ERROR)
 This error originated from a custom integration.
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/spotcast/__init__.py:361
Integration: Start Spotify on chromecast (documentation, issues)
First occurred: 11:19:35 PM (2 occurrences)
Last logged: 11:19:56 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1520, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 387, in start_casting
    spotify_device_id = getSpotifyConnectDeviceId(
  File "/config/custom_components/spotcast/__init__.py", line 361, in getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
```
Latest version of everything 
I've uninstalled Spotcast, rebooted, reinstalled, removed and re-added my account to the core Spotify integration
Cant play via device ID nor name

**Comment by Zip753** [comment]
I am also trying to use a second account, however after I have set it up in the Spotify Developer App I can't get `spotcast` to play the private playlist from the second account, instead I'm getting a very similar error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1520, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 143, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 193, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 180, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
```
I have checked that I'm able to play the very same private playlist from the non-default account via the media player provided by the core integration. I'm however able to play things from the default account, both via Spotify Device ID and entity ID (even though the latter is considerably slower to connect, probably because it's Chromecast and not Spotify Connect).

spotcast version `v3.6.14`
