### ISSUE TITLE
Endlessly loading

### ISSUE THREAD

**Issue by Bluhme1** [fondberg/spotcast#211]
**Describe the bug**
Component won´t load

* [ x] Using latest version of spotcast
* [ x] I have setup the Spotify integration in Home Assistant
* [ x] I am using multiple accounts
* [ x] Using latest stable version of Home Assistant
* [ x] I have Spotify Premium
* [x ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [x ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

**Environment (please complete the following information):**
 - HA version: [ 2012.5.1]
 - spotcast version: [ 3.5.8]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/spotcast/__init__.py:492
Integration: Start Spotify on chromecast (documentation, issues)
First occurred: 13.05.01 (25 occurrences)
Last logged: 15.12.59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/spotcast/__init__.py", line 486, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.8/site-packages/spotify_token.py", line 18, in start_session
    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/spotcast/__init__.py", line 164, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 242, in get_devices
    client = spotipy.Spotify(auth=get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/__init__.py", line 480, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/__init__.py", line 476, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/__init__.py", line 492, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token

**Configuration**
Add your configuration

**Additional context**

**Comment by Bluhme1** [comment]
My token had expired. Sorry
