### ISSUE TITLE
Random song doesn't work 

### ISSUE THREAD

**Issue by jaypi95** [fondberg/spotcast#220]
So I'm not sure if this has something to do with Home Assistants latest upgrade but when I used the "Random Song" option I always got the following error message:

```


Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:348
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:10:54 PM (9 occurrences)
Last logged: 1:31:26 PM

    [140438986703824] 'total'
    [140438701611664] 'total'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 278, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 382, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 404, in _async_run
    return await self.script.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1216, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 350, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 414, in start_casting
    play(
  File "/config/custom_components/spotcast/__init__.py", line 348, in play
    position = random.randint(0, results["total"] - 1)
KeyError: 'total'
```

I was able to fix it by using len() on lines 348 and 345 in __init__.py:

```
if random_song:                                                             
                if uri.find("album") > 0:                                               
                    results = client.album_tracks(uri)                                  
                    position = random.randint(0, len(results) - 1)                  
                elif uri.find("playlist") > 0:                                          
                    results = client.playlist_tracks(uri)                               
                    position = random.randint(0, len(results) - 1)                      
                _LOGGER.debug("Start playback at random position: %s", position)           
            if uri.find("artist") < 1:    
```

I only have one spotify connected device so I'm not really able to test it on other hardware.

**Comment by fondberg** [comment]
Thanks for a great bugreport with a fix. those are rare. I'll test it asap

**Comment by fondberg** [comment]
I tested this now and can't reproduce it. This is what I tested with 
```
service: spotcast.start
data:
  device_name: raspotify4
  uri: spotify:album:1vHvJVBK0WnpbYFw4f4UTD
  random_song: true
```
and
```
service: spotcast.start
data:
  device_name: raspotify4
  uri: spotify:playlist:37i9dQZF1CAiFMqgF92dBd
  random_song: true
 ```
Can you send me what fails for you?

**Comment by jaypi95** [comment]
Thanks for your reply. I tested around a little bit and saw that the issue was when I copied the playlist URI from Spotify I forgot to remove a part at the end. 

That part was ```?si=a26<redacted>18``` 

It's probably some sort of tracking mechanism and without it your code works perfectly fine. If I leave it then I get the error mentioned in my first post. Since spotify doesn't have the option of "copy spotify URI" anymore you have to manually edit the link it gives you anyway. Maybe it would be helpful to add this to the README.

Thanks for the reply and sorry for wasting your time.
