### ISSUE TITLE
Error during setup of component spotcast after update to 3.6.10

### ISSUE THREAD

**Issue by arjanhagg** [fondberg/spotcast#221]
After updating Spotcast to version 3.6.10 it stopped working. The log gives the following error resulting in not starting the custom integration:

Logger: homeassistant.setup
Source: custom_components/spotcast/spotcast_controller.py:158
Integration: Start Spotify on chromecast (documentation, issues)
First occurred: 2:11:51 PM (1 occurrences)
Last logged: 2:11:51 PM

Error during setup of component spotcast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 51, in setup
    spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 158, in __init__
    accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
TypeError: 'NoneType' object does not support item assignment

**Comment by markwiese** [comment]
I have only just installed Spotcast, today, and I'm getting the same error. I tried installing an older version (3.5.7) and I still get the same error.

```
2021-06-13 22:11:15 ERROR (MainThread) [homeassistant.setup] Error during setup of component spotcast
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/spotcast/__init__.py", line 51, in setup
spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)
File "/config/custom_components/spotcast/spotcast_controller.py", line 158, in __init__
accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
TypeError: 'NoneType' object does not support item assignment
```

**Comment by davide-vh** [comment]
I've just installed Spotcast v3.6.10, same error :

Error during setup of component spotcast

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 51, in setup
    spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 158, in __init__
    accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
TypeError: 'NoneType' object does not support item assignment

**Comment by fondberg** [comment]
Released bugfix
