### ISSUE TITLE
Spotcast can't start after update

### ISSUE THREAD

**Issue by fifour-1** [fondberg/spotcast#223]
**Describe the bug**

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

HA unable to start spotcast after a spotcast update.

```
2021-06-13 17:09:13 ERROR (MainThread) [homeassistant.setup] Error during setup of component spotcast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 51, in setup
    spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 158, in __init__
    accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
TypeError: 'NoneType' object does not support item assignment
```

**Environment :**
 - HA version: 2021.6.4
 - spotcast version: 3.6.10

**Comment by javilopezalarcon** [comment]
Same error 😰

**Comment by chodong-dev** [comment]
Same error 😰

**Comment by wannesmarynen** [comment]
if you are willing to fix it yourself you could go to the filespotcast controller and replace the function __init__ with this:

`
    def __init__(self, hass, sp_dc, sp_key, accounts):
        if accounts:
            self.accounts = accounts
        self.accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
        self.hass = hass`

that fixed it for me

**Comment by chodong-dev** [comment]
@wannesmarynen, I will try it.
Thanks for your comment.

**Comment by chodong-dev** [comment]
> @wannesmarynen, I will try it.
> Thanks for your comment.

It works well. Thanks again.

**Comment by fondberg** [comment]
Can someone make a PR?

**Comment by javiges** [comment]
> if you are willing to fix it yourself you could go to the filespotcast controller and replace the function **init** with this:
> 
> ```
> def __init__(self, hass, sp_dc, sp_key, accounts): 
>     if accounts:
>         self.accounts = accounts
>     self.accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
>     self.hass = hass
> ```
> 
> that fixed it for me

what is the path of that file to modify it?  Thank you

**Comment by fondberg** [comment]
Released new version

**Comment by javiges** [comment]
> Lanzamiento de nueva versión

Tengo este error con la última update


2021-06-13 19:43:59 ERROR (MainThread) [homeassistant.setup] Setup failed for spotcast: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 200, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/spotcast/__init__.py", line 36, in <module>
    from .spotcast_controller import SpotcastController
  File "/config/custom_components/spotcast/spotcast_controller.py", line 158
    if accounts:
               ^
TabError: inconsistent use of tabs and spaces in indentation
