### ISSUE TITLE
After update isn't working at all. If I go back the last good one now not working too.

### ISSUE THREAD

**Issue by spider7611** [fondberg/spotcast#229]
**Describe the bug**

* [x ] Using latest version of spotcast
* [x ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x ] Using latest stable version of Home Assistant
* [ x] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**
After update not working for me. The last one wich was worked : 3.5.10 but if I want to go back now it isn't working too. :(

**Environment (please complete the following information):**
 - HA version: [2021.6.5 ]
 - spotcast version: [ 3.6.13]

**Configuration**
Add your configuration

**Additional context**

HA log:

`Logger: homeassistant
Source: custom_components/spotcast/spotcast_controller.py:148
Integration: Start Spotify on chromecast (documentation, issues)
First occurred: 14:55:28 (8 occurrences)
Last logged: 14:55:33

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 142, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.8/site-packages/spotify_token.py", line 18, in start_session
    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/spotcast/helpers.py", line 60, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 78, in get_devices
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 176, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 132, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 148, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token`

**Comment by spider7611** [comment]
Ok, I solve this. Must refresh the 2 secret key.
