### ISSUE TITLE
Setup failed for spotcast: unknown error

### ISSUE THREAD

**Issue by Vormillion** [fondberg/spotcast#230]
**Describe the bug**

* [X] Using latest version of spotcast
* [X] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

**Environment (please complete the following information):**
 - HA version: [2021.1.5 ]
 - spotcast version: [3.6.13]

**Additional context**
Spotcast is not initializing. Error in HA logs:

2021-06-18 16:08:02 ERROR (MainThread) [homeassistant.setup] Setup failed for spotcast: unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 166, in _async_setup_component
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 416, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/spotcast/__init__.py", line 36, in <module>
    from .spotcast_controller import SpotcastController
  File "/home/homeassistant/.homeassistant/custom_components/spotcast/spotcast_controller.py", line 102
    if devices := devices_available["devices"]:
                ^
SyntaxError: invalid syntax

**Comment by hmmbob** [comment]
Update your HA. It's outdated and missing some hooks for Spotcast.
