### ISSUE TITLE
Can't update Spotcast from 3.4.7

### ISSUE THREAD

**Issue by kmoniker** [fondberg/spotcast#234]
**Describe the bug**

* [ ] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)

**Describe the bug**
I am not sure if this is the right place for this but I'm at a loss. When I restart my HA after trying to update spotcast, the component in HACS is still 3.4.7
I'm getting this error -   Could not read manifest.json [encoding without a string argument]

I get the following errors in my log: 

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/integration.py:64
Integration: HACS (documentation, issues)
First occurred: 7:18:35 PM (1 occurrences)
Last logged: 7:18:35 PM

<Integration hacs/integration> Could not read manifest.json [encoding without a string argument]

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hacs/hacsbase/hacs.py:195
Integration: HACS (documentation, issues)
First occurred: 7:18:42 PM (1 occurrences)
Last logged: 7:18:42 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 140, in startup_tasks
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 195, in handle_critical_repositories
    critical = json.loads(critical.content)
AttributeError: 'list' object has no attribute 'content'

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/integration.py:88
Integration: HACS (documentation, issues)
First occurred: 7:19:07 PM (1 occurrences)
Last logged: 7:19:07 PM

<Integration fondberg/spotcast> Could not read manifest.json [encoding without a string argument]

**Environment (please complete the following information):**
 - HA version: [  2021.6.6]
 - spotcast version: [ 3.4.7 and 3.6,14]

**Comment by hmmbob** [comment]
Try reinstalling through HACS:
- go to HACS, check if spotcast is still there
- if yes: click the 3 small dots on the Spotcast card and choose "reinstall"
- if not: check if all files are gone under `/custom_components/spotcast' (and if not, delete them and reboot) and add spotcast again by clicking on the big blue button down below right hand side

**Comment by fondberg** [comment]
Closing due to inactivity
