### ISSUE TITLE
homeassistant.exceptions.HomeAssistantError: Could not get spotify token

### ISSUE THREAD

**Issue by Electronlibre2012** [fondberg/spotcast#239]
**Describe the bug**
"no device found" error after upgrade HA to 2021.8.0 today

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

 Logger: homeassistant
Source: custom_components/spotcast/spotcast_controller.py:148
Integration: Spotcast (documentation, issues)
First occurred: 18:51:13 (7 occurrences)
Last logged: 19:04:54
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 142, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.9/site-packages/spotify_token.py", line 18, in start_session
    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/spotcast/helpers.py", line 60, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 78, in get_devices
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 176, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 132, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 148, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token

**Environment (please complete the following information):**
 - HA version: [ 2021.8.0]
 - spotcast version: [V3.6.14 ]

**Configuration**
standard configuration

**Additional context**

any idea please? it complain about spotify token, is it from console developer token? or from spotify accound (acces for HA that i have the option to "revoke")

thanks for your help.

**Comment by hmmbob** [comment]
Try adding Spotify (the HA core one) again (or: try to relink spotify from within Home Assistant)

**Comment by Electronlibre2012** [comment]
thanks @hmmbob but as you can read, the problem is related to ```spotcast``` not ``spotify``

sp_dc and sp_key have changed...lol

just check and update in configuration.yaml

spotcast:
  sp_dc: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  sp_key: xxxxxxxxxxxxxxxxxxx

Work again like a charm!
