### ISSUE TITLE
Playback does not start

### ISSUE THREAD

**Issue by seanmccabe** [fondberg/spotcast#243]
**Describe the bug**

* [X] Using latest version of spotcast
* [X] I have setup the Spotify integration in Home Assistant
* [X] I am using multiple accounts
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I'm attaching relevant logs with level debug for component spotcast (see README)
* [X] I'm using entity_id in the service call and have tried device_name but the issue remains

Playback does not work.
I get the connection ding on the device, in Google Home can see that the Spotify App has started, but there is no playback and getting the following error in HA:

```
Logger: homeassistant.core
Source: custom_components/spotcast/spotcast_controller.py:84
Integration: Spotcast (documentation, issues)
First occurred: 8:10:38 AM (7 occurrences)
Last logged: 8:20:11 AM

Error executing service: <ServiceCall spotcast.start (c:210cf9913abf366339b547ef1cbd86af): entity_id=media_player.study_speaker, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, random_song=True, force_playback=False, ignore_fully_played=False, shuffle=False, start_volume=101, repeat=off, offset=0>
Error executing service: <ServiceCall spotcast.start (c:30f86edc9f2b6679ab1e0b330d6782c8): entity_id=media_player.study_speaker, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, random_song=True, force_playback=False, ignore_fully_played=False, shuffle=False, start_volume=101, repeat=off, offset=0>
Error executing service: <ServiceCall spotcast.start (c:28e274851927faac42b13ecb42dbd359): entity_id=media_player.study_speaker, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Error executing service: <ServiceCall spotcast.start (c:3794c15e204f7a3927849d32cd313b6d): entity_id=media_player.study_speaker, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Error executing service: <ServiceCall spotcast.start (c:c9ac0077ab2a5c4d5b57a20dd1b98db8): entity_id=media_player.study_speaker, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 143, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 202, in get_spotify_device_id
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 84, in startSpotifyController
    sp.launch_app()
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/spotify.py", line 87, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```

I've tried using the device name also, but with that I do not even get the connect ding, but can see in Google Home it has connected but no playback.
I've tried with main account and additional account. Even updated the cookies on one of the additional accounts with no success.

I have noticed that on the HA Spotify integration, it is not seeing the Chromecast devices, only devices that can directly connect to Spotify, i.e. Nvidia Shield, Amplifier and Phone.
Using the native HA integration, can play from Spotify, attempting to use one of these same devices using Spotcast fails the same way:

```
Logger: homeassistant.core
Source: custom_components/spotcast/spotcast_controller.py:84
Integration: Spotcast (documentation, issues)
First occurred: 8:10:38 AM (14 occurrences)
Last logged: 8:32:06 AM

Error executing service: <ServiceCall spotcast.start (c:62c616e2780126221df5480821d2085a): entity_id=media_player.shield, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Error executing service: <ServiceCall spotcast.start (c:732a0387efff98df039958f0005589e1): entity_id=media_player.shield, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Error executing service: <ServiceCall spotcast.start (c:2fc9bc600bb3770da01a41991ef4b657): entity_id=media_player.shield, uri=spotify:playlist:1zHKtKoXgL1HzAzG7TLSAr, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Error executing service: <ServiceCall spotcast.start (c:ac96675b43cb179578689907bb8e7fc7): entity_id=media_player.shield, uri=spotify:playlist:53Ed6dsD6wQ0tSSmgMKCYw, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Error executing service: <ServiceCall spotcast.start (c:729eccbeba8de1feff87c690329877e2): entity_id=media_player.shield, uri=spotify:playlist:53Ed6dsD6wQ0tSSmgMKCYw, force_playback=True, random_song=True, repeat=track, shuffle=True, offset=1, start_volume=50, ignore_fully_played=True>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 143, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 202, in get_spotify_device_id
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 84, in startSpotifyController
    sp.launch_app()
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/spotify.py", line 87, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```

**Environment (please complete the following information):**
 - HA version: 2021.8.1
 - spotcast version: 3.6.14

**Comment by DibblesNL** [comment]
#metoo

**Comment by hmmbob** [comment]
Duplicate of https://github.com/fondberg/spotcast/issues/241

**Comment by seanmccabe** [comment]
https://github.com/fondberg/spotcast/pull/244

Resolves the issue.
