### ISSUE TITLE
Playlist sensor error 'builtin_function_or_method' object is not iterable

### ISSUE THREAD

**Issue by snp88** [fondberg/spotcast#247]
**Describe the bug**

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**
HI all

After today spotcast update to version v3.6.15
I HA logs i see bellow entry every few seconds 

Update for sensor.playlists_sensor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 101, in update
    self._attributes["playlists"] = [{ "uri": x.uri, "name": x.name} for x in resp.items ]
TypeError: 'builtin_function_or_method' object is not iterable

**Environment (please complete the following information):**
 - HA version: [core-2021.8.8 ]
 - spotcast version: [v3.6.15]

**Configuration**

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

**Additional context**

**Comment by snp88** [comment]
all good 
thx all for fast reaction ;)
