### ISSUE TITLE
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by antonbek89** [fondberg/spotcast#252]
**Describe the bug**

* [X ] Using latest version of spotcast
* [ X] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ X] Using latest stable version of Home Assistant
* [ X] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

Try to run via Developer tools --> services 

```
service: spotcast.start
data:
  entity_id: media_player.livingroom_speaker
  uri: spotify:playlist:37i9dQZF1DX3yvAYDslnv8
  force_playback: true
  random_song: true
  repeat: track
  shuffle: true
  offset: 1
  start_volume: 50
  ignore_fully_played: true
```

**Environment (please complete the following information):**
 - HA version: [2021.9.4]
 - spotcast version: [v3.6.16 ]

**Configuration**
spotcast:
    sp_dc: !primary_sp_dc
    sp_key: !primary_sp_key

**Additional context**

Error 1 :

```

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:180
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 0:49:26 (1 occurrences)
Last logged: 0:49:26

[547284303536] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1531, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 147, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 193, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 180, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
```

Error 2:

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/spotcast/spotcast_controller.py:180
Integration: Spotcast (documentation, issues)
First occurred: 0:49:26 (1 occurrences)
Last logged: 0:49:26

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1531, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 147, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 193, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 180, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Darkfull-Dante** [comment]
Would you be able to provide a debug log? There seems to be a problem in getting the list of Spotify devices. You can check [this](https://github.com/fondberg/spotcast#enabling-debug-log) on how to

**Comment by AlphaJosh** [comment]
Let me jump in and offer my debug logs. My setup and configuration is pretty much identical.


script:
  alias: Music Friday
  sequence:
  - service: spotcast.start
    data:
      uri: 'spotify:playlist:56Bor5fbMJlJV7oryb2p3k'
      random_song: true
      shuffle: true
      start_volume: 50
      entity_id: media_player.kitchen
      
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.sensor] Getting chromecast devices
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.bedroom_tv: Bedroom  TV cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-5aaa132e0e74643756e8e42588670002._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.8.15', 8009))}, uuid='5aaa132e-0e74-6437-56e8-e42588670002', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Bedroom  TV', is_audio_group=False, is_dynamic_group=None)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.tv: TV cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-Ultra-6b645d2a5d6087c584b7b72c06465a7f._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.8.17', 8009))}, uuid='6b645d2a-5d60-87c5-84b7-b72c06465a7f', _manufacturer='Google Inc.', model_name='Chromecast Ultra', friendly_name='TV', is_audio_group=False, is_dynamic_group=None)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.playground: Playground cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-Audio-30e32f67701b0016191566fb42d9956d._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.8.34', 8009))}, uuid='30e32f67-701b-0016-1915-66fb42d9956d', _manufacturer='Google Inc.', model_name='Chromecast Audio', friendly_name='Playground', is_audio_group=False, is_dynamic_group=None)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.bedroom: Bedroom cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Home-Mini-2c0d84a8cbf618e19864281436705e47._googlecast._tcp.local.')}, uuid='2c0d84a8-cbf6-18e1-9864-281436705e47', _manufacturer=None, model_name='Google Home Mini', friendly_name='Bedroom', is_audio_group=False, is_dynamic_group=None)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.everything: Everything cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Cast-Group-7E08DCF931664F588815065D44060728._googlecast._tcp.local.')}, uuid='7e08dcf9-3166-4f58-8815-065d44060728', _manufacturer=None, model_name='Google Cast Group', friendly_name='Everything', is_audio_group=True, is_dynamic_group=False)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.bathroom: Bathroom cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Home-Mini-78c4d16754f6a2bb3d57f76839cca597._googlecast._tcp.local.')}, uuid='78c4d167-54f6-a2bb-3d57-f76839cca597', _manufacturer=None, model_name='Google Home Mini', friendly_name='Bathroom', is_audio_group=False, is_dynamic_group=None)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.kitchen: Kitchen cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Home-0869f6659502b4bd2751f5589207fcfb._googlecast._tcp.local.')}, uuid='0869f665-9502-b4bd-2751-f5589207fcfb', _manufacturer=None, model_name='Google Home', friendly_name='Kitchen', is_audio_group=False, is_dynamic_group=None)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.helpers] get_cast_devices: media_player.front: Front cast info: ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Cast-Group-5B3C6F53BC394984AD4CCAC9EA2DD004-1._googlecast._tcp.local.')}, uuid='5b3c6f53-bc39-4984-ad4c-cac9ea2dd004', _manufacturer=None, model_name='Google Cast Group', friendly_name='Front', is_audio_group=True, is_dynamic_group=False)
2021-09-16 14:35:54 DEBUG (SyncWorker_9) [custom_components.spotcast.sensor] sensor devices [ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-5aaa132e0e74643756e8e42588670002._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.8.15', 8009))}, uuid='5aaa132e-0e74-6437-56e8-e42588670002', _manufacturer='Google Inc.', model_name='Eureka Dongle', friendly_name='Bedroom  TV', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-Ultra-6b645d2a5d6087c584b7b72c06465a7f._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.8.17', 8009))}, uuid='6b645d2a-5d60-87c5-84b7-b72c06465a7f', _manufacturer='Google Inc.', model_name='Chromecast Ultra', friendly_name='TV', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Chromecast-Audio-30e32f67701b0016191566fb42d9956d._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.8.34', 8009))}, uuid='30e32f67-701b-0016-1915-66fb42d9956d', _manufacturer='Google Inc.', model_name='Chromecast Audio', friendly_name='Playground', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Home-Mini-2c0d84a8cbf618e19864281436705e47._googlecast._tcp.local.')}, uuid='2c0d84a8-cbf6-18e1-9864-281436705e47', _manufacturer=None, model_name='Google Home Mini', friendly_name='Bedroom', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Cast-Group-7E08DCF931664F588815065D44060728._googlecast._tcp.local.')}, uuid='7e08dcf9-3166-4f58-8815-065d44060728', _manufacturer=None, model_name='Google Cast Group', friendly_name='Everything', is_audio_group=True, is_dynamic_group=False), ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Home-Mini-78c4d16754f6a2bb3d57f76839cca597._googlecast._tcp.local.')}, uuid='78c4d167-54f6-a2bb-3d57-f76839cca597', _manufacturer=None, model_name='Google Home Mini', friendly_name='Bathroom', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Home-0869f6659502b4bd2751f5589207fcfb._googlecast._tcp.local.')}, uuid='0869f665-9502-b4bd-2751-f5589207fcfb', _manufacturer=None, model_name='Google Home', friendly_name='Kitchen', is_audio_group=False, is_dynamic_group=None), ChromecastInfo(services={ServiceInfo(type='mdns', data='Google-Cast-Group-5B3C6F53BC394984AD4CCAC9EA2DD004-1._googlecast._tcp.local.')}, uuid='5b3c6f53-bc39-4984-ad4c-cac9ea2dd004', _manufacturer=None, model_name='Google Cast Group', friendly_name='Front', is_audio_group=True, is_dynamic_group=False)]
2021-09-16 14:35:54 DEBUG (SyncWorker_10) [custom_components.spotcast.sensor] Getting playlists
2021-09-16 14:35:54 DEBUG (SyncWorker_10) [custom_components.spotcast.spotcast_controller] setting up with  account default
2021-09-16 14:35:54 DEBUG (SyncWorker_10) [custom_components.spotcast.spotcast_controller] expires: 1631761123 time: 1631759754.3706305
2021-09-16 14:36:11 DEBUG (SyncWorker_9) [custom_components.spotcast.spotcast_controller] setting up with  account default
2021-09-16 14:36:11 DEBUG (SyncWorker_9) [custom_components.spotcast.spotcast_controller] expires: 1631761123 time: 1631759771.0472062
2021-09-16 14:36:11 DEBUG (SyncWorker_9) [custom_components.spotcast.spotcast_controller] setting up with  account default
2021-09-16 14:36:11 ERROR (MainThread) [homeassistant.components.script.music_friday] Music Friday: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1531, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 147, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 193, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 180, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
2021-09-16 14:36:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 411, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1531, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 147, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 193, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 180, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by AlphaJosh** [comment]
Note: issue unaffected after disabling random and shuffle

**Comment by Darkfull-Dante** [comment]
I think I see the problem, it seems that spotcast can't find any spotify connect devices under your spotify HA integration. I'm going to ask question just for a base line, they might seem silly, but I want to make sure:

- [ ] Do you have the official Spotify Integration in Home Assistant up and running
- [ ] If you play music in any spotify app (phone or computer) and then go in dev tools and search for media_player.[name of your spotify integration]:
     - [ ] the status is playing
     - [ ] can you see a list of available devices with at least the device currently playing the music
     - [ ] you can see the details of your media playing

**Comment by AlphaJosh** [comment]
Woohoo RESOLVED (for me)
Spotify Integration wasnt installed. I installed the Spotify Integration and got an error showing Abort and the Integration didnt install.
I am using a Spotify Family Account so checked I could install the Spotify Integration with the main Spotify account and I could.
I think reconfigured my sp_dc etc and restarted and now it works!

For your reference, I could previously see the songs that were playing on my media_player.kitchen and it showed the status and it was Spotify that was being played.

**Comment by Darkfull-Dante** [comment]
Thank you for the information, I'll check to add an error log in this case. Also if an error management would be possible

**Comment by Darkfull-Dante** [comment]
worked on a branch in my fork [corr_252](https://github.com/darkfull-dante/spotcast/tree/corr_252). The correction includes 2 elements:
- added an error message when no spotify media player is not found
- forced a return none at the end get_spotify_devices
- managed if get_spotify_devices return none in _getSpotifyConnectDeviceId

**Comment by fondberg** [comment]
I guess we can add a check on init to see that the spotify integration is installed...
