### ISSUE TITLE
Spotcast does not longer work with Google Cast

### ISSUE THREAD

**Issue by XalaTheShepard** [fondberg/spotcast#279]
**Describe the bug**
After the update to HA Core 2021.12.2 I noticed that when I use Spotcast my Google Cast devices are misbehaving (no title and cover, no possibility to play/ pause, no possibility to stop the media player. The latest Spotcast update solved this issue, but it reappeared after the update to HA Core 2021.12.3
After this HA Core issue I have reinstalled the latest Spotcast version and now everything is working fine again. 
My guess this is an issue that should be looked into by both teams. 
I am using only one account and have the latest versions of HassOS, HA Core, Supervisor and Spotcast installed.

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

**Environment (please complete the following information):**
 - HA version: [ ]
 - spotcast version: [ ]

**Configuration**
Add your configuration

**Additional context**

**Comment by hmmbob** [comment]
I'm confused.

Is it or isn't it working at this time?

**Comment by XalaTheShepard** [comment]
I know it is confusing. 
After HA Core 2021.12.2 it only works of you manually reinstall the latest version of Spotcast after the update. 
If you perform an update of HA core Spotcast no longer works with Google Cast unless you manually reinstall the latest version of Spotcast afterwards and reboot.
I think this is an issue that should be looked into by both teams, because if this issue persists the Spotcast users will always have to manually reinstall the latest Spotcast integration after every HA Core update.

**Comment by Darkfull-Dante** [comment]
Can you provide a more concise description of the bug you're facing? Please note also that Spotcast only deals with starting the playback, nothing else, we are not responsible for managing the media control after, that is managed by the Spotify integration managed by Home Assistant directly.

Can you please provide a sample of the media request sent through Spotcast, there might be something we can check with that if we can replicate the behavior? Because I never faced that behavior after update and I dailydrive that project on my personal installation.

Do you have any error logs when trying to play/plause, stop the media player, etc.?

Finally, we have a template for issues, please do not remove elements of it and only edit the relevant parts, it helps us to troubleshoot and check potentially missing information. I edited your ticket to insert back the missing parts, please fill in the form with the missing information to your level of knowledge and comfort to provide information.

**Comment by hmmbob** [comment]
> I know it is confusing. After HA Core 2021.12.2 it only works of you manually reinstall the latest version of Spotcast after the update. If you perform an update of HA core Spotcast no longer works with Google Cast unless you manually reinstall the latest version of Spotcast afterwards and reboot. I think this is an issue that should be looked into by both teams, because if this issue persists the Spotcast users will always have to manually reinstall the latest Spotcast integration after every HA Core update.

I was still running 2021.12.2 and just upgraded to 2021.12.3 - did not see the same issue. 

Would be interested to see the info requested by Felix above.

**Comment by XalaTheShepard** [comment]
To replicate the issue, I will have to downgrade my HA Core again and update it again. Spotcast was able to start, but incorrect media data and sometimes no media data at all is provided. Also pausing the media or shutting down the media player was no longer possible. Every time I try to pause or shut it down, I received the message that the process was failed. It seemed like the media player was completely frozen. Furthermore, it happened twice after the latest update that media was not only playing on the dedicated media player, but also another one. I thought it was only a Google Cast issue, but every time this issue occurs and I reinstall the latest spotcasts integration, everything is working fine again.

**Comment by hmmbob** [comment]
As explained before, Spotcast doesn't handle all of that.

What card are you using to control Spotify?

**Comment by XalaTheShepard** [comment]
I have the Spotify card on my dashboard, but mostly use the Spotcast start service in combination with an Aqara cube

**Comment by XalaTheShepard** [comment]
Both cause the same issue

**Comment by hmmbob** [comment]
We'll need debug logs when this happens to be able to properly debug.

**Comment by Darkfull-Dante** [comment]
> I have the Spotify card on my dashboard, but mostly use the Spotcast start service in combination with an Aqara cube

@XalaTheShepard, can you provide a sample of the spotcast.start service that you use. As state by hmmbob and me, we both had done the update to 2021.12.3 without Spotcast breaking. Also a sample of the configuration itself would be useful (obviously obfuscate the different tokens)

Also, the Aqara cube itself is irrelevant to the issue, it is just an input device, the service call behind is what is important, what we need to know:

1. What action did you do (the service call itself, ideally the yaml of the service call)?
2. What was the result (including logs, especially error logs)?
3. What were you expecting as a result?

And again, all the issues you seem to have (the ones you told us about) don't seem to be related to Spotcast itself. When the bug happens, did you try to control playback that was started from another source?

If the media playback starts, Spotcast did its job and exited without error (usually). Media element like artwork, and titles, playback control and media_player control (turn off, volumes) are not handled by Spotcast but by the media_player and Spotify integrations.

**Comment by Darkfull-Dante** [comment]
If you are unable to provide the information for the moment, we will have to wait for the next home assistant update that should be in January now.

When the next HA update is out, would you be able to test again if the problem persists and get back to us. We will probably ask for information while your server experience the error.

**Comment by fabiopedrosa** [comment]
I just started seeing the same issue:

```
2021-12-20 09:43:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [545547535312] Could not get spotify token
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 142, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.9/site-packages/spotify_token.py", line 20, in start_session
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://open.spotify.com/get_access_token
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1534, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 152, in start_casting
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 176, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 132, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 148, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token
```

**Comment by hmmbob** [comment]
It's not the same issue, you ran into a (temporarily) Spotify disruption. Should auto-resolve.

```
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://open.spotify.com/get_access_token
```

**Comment by hmmbob** [comment]
No worries, good to check anyways!

**Comment by hmmbob** [comment]
Thinking out loud as well: it could also be some kind of caching issue in the frontend media_player card, possibly.

It's a strange issue Robin, that's for sure! Did you ever try what happens if you reboot HA without reinstalling spotcast?

**Comment by XalaTheShepard** [comment]
I have tried rebooting HA without reinstalling the Spotcast integration, but in this case the issue persists.

**Comment by Darkfull-Dante** [comment]
ok, so the problem seems to be in your reboot process not in the update process. Can you check your log journal (complete view) and do a search (`ctrl+f` in most browser) for Spotify and return the lines that match the search.

You should have something that looks like:
```yaml
2021-12-20 09:03:23 INFO (MainThread) [homeassistant.setup] Setting up spotify
2021-12-20 09:03:23 INFO (MainThread) [homeassistant.setup] Setup of domain spotify took 0.0 seconds
[...]
# i might have to lines, because I have 2 spotify accounts setup
2021-12-20 09:03:25 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.spotify
2021-12-20 09:03:25 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.spotify
```

**Comment by XalaTheShepard** [comment]
Dear, 

Many thanks for your support. 
I have copied all the lines with regard to Spotify from the complete log below. 
Please note that I am still in the situation that everything works as it should due to a reinstall of Spotcast. 
If no issues are found in this log, I will downgrade the HA Core tomorrow to simulate the issue (today is impossible due to some appointments) and I will copy the logs when the issue is still happening. 

Kind regards, 

Robin

2021-12-20 15:03:12 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'usb', 'input_select', 'input_boolean', 'risco', 'binary_sensor', 'zone', 'input_text', 'duckdns', 'broadlink', 'somfy', 'ifttt', 'nest', 'localtuya', 'synology_dsm', 'ytube_music_player', 'mobile_app', 'input_number', 'input_datetime', 'ssdp', 'stream', 'timer', 'camera', 'google_assistant', 'co2signal', 'spotify', 'dahua', 'onvif', 'persistent_notification', 'automation', 'script', 'sensor', 'blueprint', 'shelly', 'buienradar', 'tts', 'spotcast', 'google_home', 'scene', 'ipp', 'brother', 'adguard', 'cast', 'ffmpeg', 'auto_backup', 'dhcp', 'uptimerobot', 'smartir', 'met', 'updater', 'zeroconf', 'hacs', 'smartthinq_sensors', 'trace', 'tahoma', 'configurator', 'media_source', 'system_health', 'plex', 'history', 'google', 'map', 'webostv', 'netatmo', 'default_config', 'accuweather', 'group', 'spacex', 'openweathermap', 'ps4', 'energy', 'speedtestdotnet', 'logbook', 'tuya', 'notify', 'mqtt', 'my', 'skodaconnect', 'wake_on_lan', 'counter', 'tag', 'zha', 'media_player', 'sun', 'network'}
2021-12-20 15:03:58 INFO (MainThread) [homeassistant.setup] Setting up spotify
2021-12-20 15:03:58 INFO (MainThread) [homeassistant.setup] Setup of domain spotify took 0.0 seconds
2021-12-20 15:04:05 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.spotify
2021-12-20 15:04:36 INFO (MainThread) [homeassistant.components.automation.spotify_connect_running] Initialized trigger Spotify Connect running
2021-12-20 15:04:36 INFO (MainThread) [homeassistant.components.automation.spotify_connect_update] Initialized trigger Spotify Connect update
2021-12-20 15:05:14 WARNING (MainThread) [homeassistant.components.input_select] Current option: loading no longer valid (possible options: Living room, Remote master bedroom TV, PlayStation 4, Spotify Robin De Becker, Living Room TV, Master bedroom TV, Living Google TV, Basement, Living Room TV, Plex (Plex Web - Chrome - Windows), Plex (Plex for LG - webOS), Plex (Plex for Android (Mobile) - P9 Plus), Plex (Plex Cast - Chromecast), Plex (Plex for Android (Mobile) - Mi A2 Lite), Plex (Plex for Android (Mobile) - M2101K9AG), Plex (Plex Web - Chrome - Windows), Plex (Plex Cast - Chromecast), Chromecast3338, Plex (Plex for Android (TV) - Chromecast), Plex (Plex Web - Chrome - Windows), Plex (Plex Web - Chrome - Windows))

**Comment by XalaTheShepard** [comment]
Dear all, 

May I request to put this issue on hold for a few days? 
Today a new version of HA Core (2021.12.4) has been released. 
It contained an update of Pychromecast. 
At this moment it looks like this update solved the issue, but I will follow it up for a few days to see if the issue still occurs. 

Many thanks for your support. 

Kind regards, 

Robin

**Comment by hmmbob** [comment]
It's probably not the `pychromecast` bump, but the revert of using the Home Assistant Media Player app usage

https://github.com/home-assistant/core/pull/62385

**Comment by Darkfull-Dante** [comment]
Due to lack of repeatability and that the issue seems to have resolved itself for the time being I will close the issue, please comment mentioning me if it surfaces again
