### ISSUE TITLE
Error if category specified without country

### ISSUE THREAD

**Issue by jazzyisj** [fondberg/spotcast#300]
**Describe the bug**
Call spotcast.start with category but no country specified produces error.

* [X] Using latest version of spotcast
* [X] I have setup the Spotify integration in Home Assistant
* [X] I am using multiple accounts
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I'm attaching relevant logs with level debug for component spotcast (see README)
* [X] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**
When calling spotcast.start specifying category but no country error is generated, no playback.

**Environment (please complete the following information):**
 - Installation type: HA_OS
 - HA version: [2022.2.7 ]
 - spotcast version: [v3.6.25 ]

**Configuration**
```
spotcast:
  sp_dc: !secret HASSIO_SP_DC
  sp_key: !secret HASSIO_SP_KEY
  accounts:
    hassio:
      sp_dc: !secret HASSIO_SP_DC
      sp_key: !secret HASSIO_SP_KEY
    jazzyisj:
      sp_dc: !secret JAZZYISJ_SP_DC
      sp_key: !secret JAZZYISJ_SP_KEY
    sherigagnon:
      sp_dc: !secret SHERI_SP_DC
      sp_key: !secret SHERI_SP_KEY
```
**Additional context**

Service Call
```
service: spotcast.start
data:
  entity_id: media_player.dining_room_hub
  category: rock
  limit: 20
```
Error Log
```
2022-02-16 22:43:32 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 372, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 575, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 197, in start_casting
    uri = helpers.get_random_playlist_from_category(client, category, country, limit)
  File "/config/custom_components/spotcast/helpers.py", line 129, in get_random_playlist_from_category
    if country.upper() not in spotify_client.country_codes:
AttributeError: 'NoneType' object has no attribute 'upper'
2022-02-16 22:43:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473296478656] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 534, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1253, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 354, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 372, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 575, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 197, in start_casting
    uri = helpers.get_random_playlist_from_category(client, category, country, limit)
  File "/config/custom_components/spotcast/helpers.py", line 129, in get_random_playlist_from_category
    if country.upper() not in spotify_client.country_codes:
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by fcusson** [comment]
A fix is in work for this problem
