### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Flagun** [fondberg/spotcast#321]
# Bug Ticket
I added a new account to Home Assistant and after that the spotcast stoped working.
## Describe the bug
Here is the log entry for the error: 
2022-04-21 10:56:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1604138968] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1677, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [x] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [x] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ ]
 - spotcast version: [ ]

## Configuration

spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key:  !secret primary_sp_key
#  country: PL #optional, added in 3.6.24
  accounts:
    theflagun:
      sp_dc: !secret flagun_sp_dc
      sp_key: !secret flagun_sp_key

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

**Comment by Flagun** [comment]
OK got it working. When I created a new spotify integration in HA it was disabled by default - everything works when it was enabled.
