### ISSUE TITLE
Failed to call service spotcast/start (400 Client Error)

### ISSUE THREAD

**Issue by senoadiw** [fondberg/spotcast#33]
Hi,

I'm unable to call the spotcast.start service on Home Assistant 0.99.3 docker image and spotcast 2.2 (installed via HACS 0.14.2) due to the following error `Failed to call service spotcast/start. 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login`

The service parameters I tried:

```
{
  "entity_id": "media_player.chromecast",
  "uri": "spotify:playlist:37i9dQZF1DWXRqgorJj26U"
}
```

Previously I had no issue setting up the Spotify media player component (https://www.home-assistant.io/components/spotify/) and can control the playback on my chromecast source. Googling around show this past issue that has been resolved https://github.com/balloob/pychromecast/issues/264.

Please find the following error log upon the spotcast.start service:

```

2019-09-26 19:11:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1852038640] 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service,
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call,
    await asyncio.shield(self._execute_service(handler, service_call)),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service,
    await self._hass.async_add_executor_job(handler.func, service_call),
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
  File "/config/custom_components/spotcast/__init__.py", line 162, in start_casting,
    access_token, expires = get_spotify_token(username=user, password=pwd),
    data = st.start_session(username, password),
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 69, in start_session,
    _login(session, cookies, username, password, token),
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 31, in _login,
    response.raise_for_status(),
    raise HTTPError(http_error_msg, response=self),
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login
```

Cheers

**Comment by senoadiw** [comment]
After further searching I came upon this post https://community.home-assistant.io/t/spotcast-custom-component-to-start-playback-on-an-idle-chromecast-device/114232/158

Seems like an issue due to conflicts between spotipy_homeassistant and  fondberg_spotipy packages? Not sure if it is okay to replace spotipy_homeassistant manually in the docker container?

```
docker exec -it homeassistant bash
pip list
...
spotipy-homeassistant            2.4.4.dev1
...
pip uninstall spotipy-homeassistant
pip install fondberg-spotipy==2.4.5-dev2
```

**Comment by fredamn76** [comment]
i have this issue aswell

**Comment by fondberg** [comment]
The community post is from me...

Just to make sure, do you have premium account or free?

**Comment by senoadiw** [comment]
Yes, I use my premium account. The HA Spotify player component works fine
with it.

**Comment by fondberg** [comment]
Can you try with the latest V2.3 release?

**Comment by senoadiw** [comment]
> Can you try with the latest V2.3 release?

Hi @fondberg, I've upgraded to spotcast v2.3 via HACS and rebooted HA. Still having the same error:

```
2019-10-07 06:40:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1852459248] 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service,
    connection.context(msg),,
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call,
    await asyncio.shield(self._execute_service(handler, service_call)),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/config/custom_components/spotcast/__init__.py", line 161, in start_casting,
    access_token, expires = get_spotify_token(username=user, password=pwd),
  File "/config/custom_components/spotcast/__init__.py", line 84, in get_spotify_token,
    data = start_session(username, password),
  File "/config/custom_components/spotcast/spotify_token.py", line 86, in start_session,
    _login(session, cookies, username, password, token),
  File "/config/custom_components/spotcast/spotify_token.py", line 44, in _login,
    response.raise_for_status(),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status,
    raise HTTPError(http_error_msg, response=self),
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login
```

**Comment by fondberg** [comment]
Looks like wrong credentials.
Can you add the following to the file __init__.py to get some debug output?
```
import http.client as http_client
http_client.HTTPConnection.debuglevel = 1
```

**Comment by senoadiw** [comment]
> Looks like wrong credentials.

@fondberg you made me check again and indeed and the problem was a bad character in spotify_username in my secrets.yaml. I fixed it and rebooted HA, now spotcast works fine. I think some bad login credentials exception handling would be nice in this case. Thanks again for checking out the issue.

Cheers

**Comment by stef97** [comment]
I am having this issue also 
I have a premium account checked the password, ( by loging in from my PC)enabled debug but still the errors are there
I do have an ! in the password so I used double quotes in secrets 
This was working fine until 3 days ago 
Any extra suggestion would be useful 
Many thanks
`2020-04-29 16:48:56 ERROR (MainThread) [homeassistant.components.automation] wakeup: Error executing script. Unexpected error for call_service at pos 3: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1247, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1286, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 167, in start_casting
    access_token, expires = get_spotify_token(username=user, password=pwd)
  File "/config/custom_components/spotcast/__init__.py", line 86, in get_spotify_token
    data = st.start_session(username, password)
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 75, in start_session
    _login(session, cookies, username, password, token)
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 33, in _login
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login

**Comment by metec22** [comment]
I am also seeing this error. It was working without issue up until a few days ago.

**Comment by hampetorp** [comment]
@stef97 I have the same problem as you. I tried to change the password and removed the !, but still same problem.
I have noticed that I never need to click on the "authenticate" button on my spotify card anymore. Maybe that can have something to do with this issue?

**Comment by Gulivert** [comment]
In my case, it use to work fine, but since the last update, it stop to work and start to send me the same message

**Comment by cvtroche** [comment]
I am having the same issue, it worked fine for about 2 days then spotify made me reset my password and now i cant get it to work. im getting the same error. i changed it in my config to the new login, reinstalled spotify addon and spotcast addon and still cant get it to work

**Comment by kaflake** [comment]
I have the problem, too. Always this error message

**Comment by maorcc** [comment]
Since the problem reappears for many just in the last few days, it is probably a different bug, and therefore a new Issue should be opened.  This one is already Closed.

**Comment by oederp1** [comment]
I have the same problem too.
Always i get this error.

**Comment by 6arcaxavi** [comment]
Hey everyone!
Just leaving a note that you may find more info here:
 - https://github.com/fondberg/spotcast/issues/84
Or maybe here: https://github.com/enriquegh/spotify-webplayer-token/issues/6
It looks like it's a common problem, based on a change on the side of Spotify.
