### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by blautob** [fondberg/spotcast#331]
# Bug Ticket

## Describe the bug

* [ x] Using latest version of spotcast
* [ x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ x] Using latest stable version of Home Assistant
* [ x] I have Spotify Premium
* [ x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ x] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS
 - HA version: [ 2022.6.6]
 - spotcast version: [ 3.6.29]

## Configuration

simple standard config 
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

## Service Call

service: spotcast.start
data:
  uri: spotify:track:5ZSzAggKFjyIL6OLA2xUUg
  entity_id: media_player.kuche

## Additional context

Cant get this to work.
Reinstalled spotify component and reset cookies, restarted several times.
This is the error i receive

[1670581912] Error handling message: Unknown error (unknown_error)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1747, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by Sholofly** [comment]
@blautob I had the same. I had disabled the spotify media_player manually. After setting it to hidden it worked again.

**Comment by ahaverty** [comment]
I'm hitting this issue with spotcast also. My Spotify integration is automatically disabled, even after re-installing.
For me, it's a Spotify rate limit issue, which is being tracked over here: https://github.com/home-assistant/core/issues/73319

**Comment by ahaverty** [comment]
Just in case anyone has that same spotify integration issue which would cause this spotcast issue, I have figured out a fix that works for me and at least one other person so far: https://github.com/home-assistant/core/issues/73319#issuecomment-1191990161

**Comment by blautob** [comment]
> Just in case anyone has that same spotify integration issue which would cause this spotcast issue, I have figured out a fix that works for me and at least one other person so far: [home-assistant/core#73319 (comment)](https://github.com/home-assistant/core/issues/73319#issuecomment-1191990161)

wow this worked for me. thx

**Comment by fcusson** [comment]
Should be resolved in `v3.7.0`. Please reopen if still present.
