### ISSUE TITLE
Unable to play media from Spotify but working and visible on devices if started from elsewhere

### ISSUE THREAD

**Issue by nicwats** [fondberg/spotcast#332]
# Bug Ticket

## Describe the bug

* [X] Using latest version of spotcast
* [X] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

I've tried removing the Spotify integration & Spotcast entirely, restarting and reinstalling following all the steps but suffering the same issuee. I've tried the Spotify Lovelace Card and Mini Media Player card but suffer the same issue. Account link to spotify seems fine in that I can follow Browse Media>Cast>Spotify and see all the playlists etc. however when I click the play button on any of the items, nothing happens. Not sure if it's an issue with the Spotify Integration or Spotcast but having read everything I can find and tried sorting things out with my limited knowledge, I'm somewhat out of ideas! Any advice would be great. I did have a look at ticket 244 as it sounded similar but it looks like the fixes for that are already incorporated into the release that I'm using. 

## Environment

 - Installation type: [Home Assistant on RPi 3]
 - HA version: [2022.7.3]
 - spotcast version: [3.6.29]

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

`This error originated from a custom integration.
Logger: homeassistant.core
Source: custom_components/spotcast/spotcast_controller.py:187
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues))
First occurred: 11:31:58 (52 occurrences)
Last logged: 13:24:41

Error executing service: <ServiceCall spotcast.start (c:01G7PGD91KTR6YPHMA6Y6M9BNF): entity_id=media_player.downstairs, uri=spotify:playlist:4kU1Gu5bEGdUbrKnxNIo4Y, ignore_fully_played=False, shuffle=False, start_volume=101, random_song=False, repeat=off, offset=0, limit=20, force_playback=False>
Error executing service: <ServiceCall spotcast.start (c:01G7PGD9HDQK86NHTM4CZ0CJDT): entity_id=media_player.downstairs, uri=spotify:playlist:4kU1Gu5bEGdUbrKnxNIo4Y, ignore_fully_played=False, shuffle=False, start_volume=101, random_song=False, repeat=off, offset=0, limit=20, force_playback=False>
Error executing service: <ServiceCall spotcast.start (c:01G7PKG0YKPWK3EFNY18S3278H): entity_id=media_player.downstairs, uri=spotify:playlist:4kU1Gu5bEGdUbrKnxNIo4Y, ignore_fully_played=False, shuffle=False, start_volume=101, random_song=False, repeat=off, offset=0, limit=20, force_playback=False>
Error executing service: <ServiceCall spotcast.start (c:01G7PKG1ENA8DE4ZPNAXGYYT8S): entity_id=media_player.downstairs, uri=spotify:playlist:4kU1Gu5bEGdUbrKnxNIo4Y, ignore_fully_played=False, shuffle=False, start_volume=101, random_song=False, repeat=off, offset=0, limit=20, force_playback=False>
Error executing service: <ServiceCall spotcast.start (c:01G7PKG1XSSYGBGFPXMV0AP428): entity_id=media_player.downstairs, uri=spotify:playlist:4kU1Gu5bEGdUbrKnxNIo4Y, ignore_fully_played=False, shuffle=False, start_volume=101, random_song=False, repeat=off, offset=0, limit=20, force_playback=False>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable`

**Comment by nicwats** [comment]
I'm an idiot, its one of the items mentioned as a comment at the very bottom of one of the previous issues in that the spotify media player had been disabled (though I hadn't done that myself so not sure why it ended up in that state).
Brief description of the fix in case it helps anyone: 
Go to Settings>Devices&Services>Entities Tab Click on the three lines in the shape of a triangle at top right and select 'Show Hidden Entities' and 'Show Disabled Entities'. 
Find media_player.spotify_xxxx in the list, select it, go to advanced settings and change status from 'Disabled' to either 'Hidden' or 'Enabled'. It should then all be running correctly again.
