### ISSUE TITLE
Spotcast cannot find Chromecast devices by entity ID

### ISSUE THREAD

**Issue by chadbaum** [fondberg/spotcast#333]
I cannot use the media browser to start playback using Spotcast on Chromecast devices.  It works fine using the other methods of identifying devices in automations, however, it looks like the media browser will always use entity ID and that is what is broken for me.  Device in this example is a Google Home Mini.

The log will produce the following error:

```log
2022-07-19 08:12:13 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01G8B5YZMFCC3RA6RAK2QS7E97): entity_id=media_player.office, uri=spotify:track:6habFhsOp2NvshLv26DqMb, repeat=off, force_playback=False, offset=0, limit=20, ignore_fully_played=False, start_volume=101, random_song=False, shuffle=False>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 203, in get_spotify_device_id
    spotify_cast_device = SpotifyCastDevice(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 55, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 81, in getChromecastDevice
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Could not find device with name Speaker - Office
```

## Environment

 - Installation type: [Container]
 - HA version: [latest ]
 - spotcast version: [latest ]

**Comment by ajkelsey** [comment]
If you have a custom name for the device, it doesn't work. I had the same trouble and removed my custom name and it worked after that.

**Comment by chadbaum** [comment]
> If you have a custom name for the device, it doesn't work. I had the same trouble and removed my custom name and it worked after that.

Thanks, you're totally right.  I reverted the custom name for the entity and it works fine now.  

Any chance we can get custom name support?  It messes up my naming conventions in HA. :)

**Comment by fcusson** [comment]
The custom name support is with the Spotify ID. The entity ID was added later for wase of use, but is reliant on the correct namming of the device.
