### ISSUE TITLE
receive "unknown error" when trying to play

### ISSUE THREAD

**Issue by gmcaesar** [fondberg/spotcast#335]
# Bug Ticket

## when use play receives "unknown error"

* [x ] Using latest version of spotcast
* [x ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x ] Using latest stable version of Home Assistant
* [ x] I have Spotify Premium
* [ x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [x ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 -Home Assistant 2022.7.6 Supervisor 2022.07.0 Operating System 8.2
 - spotcast version: 3.6.29

## Configuration

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

## Service Call

service: spotcast.start
data:
  entity_id: media_player.bedroom_speaker
  uri: 01EcuDtzuP982UMLeciwaL

## Logs"
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:181
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:02:34 PM (6 occurrences)
Last logged: 9:17:15 PM

[140363455886720] Error handling message: Unknown error (unknown_error)
[140363439991312] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 181, in start_casting
    uri[1] = uri[1].lower()
IndexError: list index out of range
`

**Comment by hmmbob** [comment]
Your URI is not in accordance with how it should be formatted. Check the docs 👍🏻

**Comment by gmcaesar** [comment]
new yaml:

`service: spotcast.start
data:
  entity_id: media_player.bedroom_speaker
  uri: spotify:playlist:01EcuDtzuP982UMLeciwaL
`

 same error:


`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:187
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:00:32 PM (5 occurrences)
Last logged: 7:02:18 PM

[140363506076352] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by hmmbob** [comment]
It is not the same error though. See https://github.com/fondberg/spotcast/issues/331 for this new error.

**Comment by fcusson** [comment]
original problem resolved, second problem is a duplicate, will close issue
