### ISSUE TITLE
New error after updating HA to 2022.8.1 (or possibly 2022.8.0)

### ISSUE THREAD

**Issue by MadOtis** [fondberg/spotcast#341]
I hadn't tried in 2022.8.0, so there's that...

After updating to 2022.8.1, I noticed that my media pages involving Spotify not only stopped showing devices to play to, but also stopped showing playlists that can be selected.  I AM on the latest version of spotcast installed via HACS (v3.6.29)  So, I started looking at the log files.  I see a constant repeating stream of: 

```log
`2022-08-05 17:20:22.447 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 146, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.10/site-packages/spotify_token.py", line 20, in start_session
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://open.spotify.com/get_access_token?reason=transport&productType=web_player&_authfailed=1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/spotcast/helpers.py", line 91, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 98, in get_devices
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 183, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 140, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 155, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token.")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token.
2022-08-05 17:20:22.458 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved`
```

...for each time I try to click anything on the Spotify panel or any custom panels using spotcast.

This used to work flawlessly prior to updating HA.  I've checked and update my sp_dc and sp_key values in my secrets.yaml file, to no avail.  I have zero issues logging in to spotify on any other device.  Where else should I look or what more info can I provide?

**Comment by fcusson** [comment]
@MadOtis, I did regression test yesterday on HA 2022.8.1 and had no problem. Home Assistant changed the way Spotify is integrated. (no longer configurable from the configuration.yaml file). Can you try reconfiguring Spotify Integration (not Spotcast) and reattempt?

**Comment by jamesyakub** [comment]
I am having a similar issue. I think it might be linked to issue #322.

My logs are similar to the above e.g.
 `Logger: aiohttp.server
Source: custom_components/spotcast/spotcast_controller.py:155
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues))
First occurred: 19:55:58 (1 occurrences)
Last logged: 19:55:58

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 146, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.10/site-packages/spotify_token.py", line 20, in start_session
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://open.spotify.com/get_access_token?reason=transport&productType=web_player&_authfailed=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 325, in post
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 170, in start_casting
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 183, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 140, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 155, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token.")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token.`

but I also have the following warning regarding pychromecast, not sure if @MadOtis has this to?:

`Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py:672
First occurred: 19:56:50 (4 occurrences)
Last logged: 19:59:36

[TV(192.168.1.123):8009] Heartbeat timeout, resetting connection`

I am running home assistant os on a rasberry pi.
I have Spotify integration updating and working without the configuration.yaml. 
I also updated the sp_dc and sp_key values just in case. But not working.

Let me know if I can do anything to help identify the issue.

**Comment by accelle17** [comment]
Also the same log as the first ones. I already tried removing the three spotify integrations and re-adding them. Still giving the same error after restart.

I'm on 2022.08 and spotcast 3.6.29.

**Comment by snp88** [comment]
the same error i have on 2022.08.2 
spotify integration is configured via UI not Yaml

**Comment by hmmbob** [comment]
I am running on 2022.8.2 and latest spotcast - not seeing this error and spotcast plays fine, so it is not a generic error.

A *401 Unauthorized* error does indicate something is wrong with your access tokens. I've seen (in different forums) that a lot of old tokens expired recently - please ensure you update all `sp_dc` and `sp_key` values, even if you updated recently. Make sure you don't logout of the session in which you are grabbing these tokens, as their validity will be revoked if you do so! I prefer the `incognito` method described here: https://github.com/fondberg/spotcast#incognito-mode. Pay attention to step 6: `"Close the window without logging out (Otherwise the cookies are made invalid)"`. Restart homeassistant after updating the tokens in your config.

If this doesn't help, please try re-adding the Spotify integration following all steps in these *updated* docs: https://www.home-assistant.io/integrations/spotify/

**Comment by snp88** [comment]
what is interesting even having this error the component looks like it works :) 
shows me all chromecast devices I can play music on them
![image](https://user-images.githubusercontent.com/46537540/183390151-4833a983-5708-45ef-9646-d5056da8a066.png)

**Comment by accelle17** [comment]
Fix, I had to renew the sp_dc and sp_key, probably this is the only one needed to fix it.

**Comment by snp88** [comment]
> Fix, I had to renew the sp_dc and sp_key, probably this is the only one needed to fix it.

Confirm

**Comment by MadOtis** [comment]
I guess this could be closed.  I did indeed renew sp_dc and sp_key values several times with restarts of HA in between with no luck.  However, It's possible I did get values from old cookies, because the 1 time I did the exact same thing via the Incognito window it started working (However, of note:  Following the Incognito instructions, there was never any calls to "get_access_token" in the developer console even after several login-logout cycles.  But, I was able to retrieve values from the correct cookie values from "open.spotify.com" which WAS found in each requests.

**Comment by jamesyakub** [comment]
thanks I had been logging out when cycling through the accounts. updating the sp_dc and sp_key has stopped this issue.

Thanks for the helpful responses.

**Comment by accelle17** [comment]
> get_access_token

I've been trying to filter this one too on incognito but it's zero result. I checked application instead of network and it displayed the cookies of spotify and that's where I found the dc and keys.

**Comment by hmmbob** [comment]
> > get_access_token
> 
> I've been trying to filter this one too on incognito but it's zero result. I checked application instead of network and it displayed the cookies of spotify and that's where I found the dc and keys.

I've taken a go to better explain the steps needed in https://github.com/fondberg/spotcast/pull/342
