### ISSUE TITLE
stoped working after 2022.8.6??

### ISSUE THREAD

**Issue by Bluhme1** [fondberg/spotcast#344]
Got following error

Logger: homeassistant
Source: custom_components/spotcast/spotcast_controller.py:155 
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues)) 
First occurred: 21.59.50 (5 occurrences) 
Last logged: 22.19.35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 146, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.10/site-packages/spotify_token.py", line 20, in start_session
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://open.spotify.com/get_access_token?reason=transport&productType=web_player&_authfailed=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/spotcast/helpers.py", line 91, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 98, in get_devices
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 183, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 140, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 155, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token.")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token.Logger: homeassistant
Source: custom_components/spotcast/spotcast_controller.py:155 
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues)) 
First occurred: 21.59.50 (5 occurrences) 
Last logged: 22.19.35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 146, in get_spotify_token
    self._access_token, self._token_expires = st.start_session(
  File "/usr/local/lib/python3.10/site-packages/spotify_token.py", line 20, in start_session
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://open.spotify.com/get_access_token?reason=transport&productType=web_player&_authfailed=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/spotcast/helpers.py", line 91, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 98, in get_devices
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 183, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 140, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 136, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 155, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token.")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token.

**Comment by hmmbob** [comment]
You didn't use the issue template, that has a mandatory check that you have renewed your `sp_dc` and `sp_key` values and restarted Home Assistant (see README).

As a 401 error has to do with failed authentication, please cycle your keys (and make sure to no log out, it will destroy the keys again)

**Comment by Bluhme1** [comment]
Sorry. Did what you recommended. Everything works again
Thank you

**Comment by hmmbob** [comment]
Glad it helped!
