### ISSUE TITLE
SpotifyException: http status: 429 - too many 502 error responses

### ISSUE THREAD

**Issue by selfisch** [fondberg/spotcast#352]
# Bug Ticket

## Describe the bug

* [ x ] Using latest version of spotcast
* [ x ] Using latest stable version of Home Assistant
* [ x ] I have setup the Spotify integration in Home Assistant
* [ x ] I have Spotify Premium
* [ x ] I am using multiple accounts
* [ x ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [ x ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ x ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Supervised|
 - HA version: [ 2022.9.4 ]
 - spotcast version: [ 3.6.30 ]

## Configuration
```
spotcast:
  sp_dc: !secret spotify_main_dc
  sp_key: !secret spotify_main_key
  country: DE
  accounts:
    mum:
      sp_dc: !secret spotify_mum_dc
      sp_key: !secret spotify_mum_key
    kid1:
      sp_dc: !secret spotify_kid1_dc
      sp_key: !secret spotify_kid1_key
    kid2:
      sp_dc: !secret spotify_kid2_dc
      sp_key: !secret spotify_kid2_key
    dad:
      sp_dc: !secret spotify_main_dc
      sp_key: !secret spotify_main_key
```

## Service Call
```
service: spotcast.start
data:
  account: "kid1"
  entity_id: "media_player.kid1"
  uri: "spotify:album:37i9dQZF1DX05r4Oy3Ln97"
```

I tested it without an account definition, what works.

## Additional context
```
2022-09-15 13:02:57.167 ERROR (Thread-21) [pychromecast.socket_client] [([::ffff:a00:147c]):8009] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:a00:147c]', 8009)), retrying in 5.0s
2022-09-15 13:03:03.674 ERROR (SyncWorker_9) [spotipy.client] Max Retries reached
2022-09-15 13:03:03.678 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01GD0D1Q2AEFTKB3BKQW4JT7FS): account=kid1, entity_id=media_player.kid1, uri=spotify:album:37i9dQZF1DX05r4Oy3Ln97, offset=0, start_volume=101, repeat=off, ignore_fully_played=False, shuffle=False, force_playback=False, limit=20, random_song=False>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/player/repeat?state=off&device_id=xxx (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 240, in _internal_call
    response = self._session.request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/player/repeat?state=off&device_id=xxx (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 245, in start_casting
    client.repeat(state=repeat, device_id=spotify_device_id)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1823, in repeat
    self._put(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 312, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 281, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/me/player/repeat?state=off&device_id=xxx:
 Max Retries, reason: too many 502 error responses
```

**Comment by fcusson** [comment]
@selfisch, 502 error usually means a bad config from your spotify dev app. Is the official Spotify Integration functional?

Can you validate that you are able to see playback details from the Spotify Integration if playing media directly from Spotify?

**Comment by selfisch** [comment]
Hey @fcusson ,
yes it is. The spotify integration is working fine. If my doughter or I play spotify stuff from our mobile for example, I can see that in home-assistant spotify card in lovelace.

But you pointed me out to a sentence in the spotify integration config at home-assistant:

> Using multiple Spotify accounts
This integration supports multiple Spotify accounts at once. You don’t need to create another Spotify application in the Spotify Developer Portal. Multiple Spotify accounts can be linked to a single Spotify application.

> You will have to add those accounts into the Users and Access section of your application in the Spotify Developer Portal.

Unfortunately, the "Users and Access" button in my spotify developer console is grayed out.

I will try to create a new application and attach it to my home-assistant, because with new apps, button is not grayed out :-). I will keep you posted.

**Comment by fcusson** [comment]
Hi @selfisch, we revamped the way we manage request to spotify_connect device in `v3.7.0`. Can you confirm if you still have your bug. I'm doing a clean-up in the ticket backlog.

**Comment by selfisch** [comment]
Hey @fcusson ,
error is gone as far as I can see. Dont know since when. But will come back if it comes up again :-).
Thanks and have nice one.
