### ISSUE TITLE
Spotcast not starting

### ISSUE THREAD

**Issue by cdn4lf** [fondberg/spotcast#359]
# Bug Ticket

## Describe the bug

Spotify is not starting music when triggered through Spotcast.  Spotify player app is also not loading.

Issue started on Monday 10/24.  Has been working correctly since last patch/issue cycle (2+ months ago I think).  No config/UI/UX/yaml changes have been made in the last 4 weeks or more.

* [X ] Using latest version of spotcast
* [ X] Using latest stable version of Home Assistant
* [ ]X I have setup the Spotify integration in Home Assistant
* [ X] I have Spotify Premium
* [ X] I am using multiple accounts
* [ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [X ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Container]
 - HA version: [2022.10.5 ]
 - spotcast version: [3.6.30 ]

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:164
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: October 24, 2022 at 6:57:47 PM (2 occurrences)
Last logged: 7:10:50 AM

[139777290243424] Could not get spotify token.
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 157, in get_spotify_token
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/config/custom_components/spotcast/spotcast_controller.py", line 177, in start_session
    raise TokenError()
custom_components.spotcast.spotcast_controller.TokenError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 170, in start_casting
    client = spotcast_controller.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 214, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 149, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 145, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 164, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token.")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token.

**Comment by hmmbob** [comment]
Obtain new sp_dc and sp_key values, as the checklist already suggests :+1:

**Comment by cdn4lf** [comment]
That worked, thank you.
