### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by milandzuris** [fondberg/spotcast#372]
````log
This error originated from a custom integration.

Logger: spotipy.client
Source: custom_components/spotcast/__init__.py:274
Integration: Spotcast (documentation, issues)
First occurred: 21:25:32 (2 occurrences)
Last logged: 21:26:30

HTTP Error for PUT to https://api.spotify.com/v1/me/player/repeat?state=off&device_id=0a4b952cd7e4134dd459d5f41007a513 with Params: {} returned 404 due to Device not found





This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/spotcast/__init__.py:274
Integration: Spotcast (documentation, issues)
First occurred: 21:25:34 (2 occurrences)
Last logged: 21:26:30

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/repeat?state=off&device_id=0a4b952cd7e4134dd459d5f41007a513: Device not found, reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/repeat?state=off&device_id=0a4b952cd7e4134dd459d5f41007a513

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 274, in start_casting
    client.repeat(state=repeat, device_id=spotify_device_id)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1832, in repeat
    self._put(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 312, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/repeat?state=off&device_id=0a4b952cd7e4134dd459d5f41007a513:
 Device not found, reason: None










Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:274
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:25:34 (2 occurrences)
Last logged: 21:26:30

[546723275504] Error handling message: Unknown error (unknown_error) from 192.168.0.4 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/repeat?state=off&device_id=0a4b952cd7e4134dd459d5f41007a513

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 274, in start_casting
    client.repeat(state=repeat, device_id=spotify_device_id)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1832, in repeat
    self._put(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 312, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/repeat?state=off&device_id=0a4b952cd7e4134dd459d5f41007a513:
 Device not found, reason: None













This error originated from a custom integration.

Logger: spotipy.client
Source: custom_components/spotcast/spotcast_controller.py:315
Integration: Spotcast (documentation, issues)
First occurred: 21:32:22 (1 occurrences)
Last logged: 21:32:22

HTTP Error for PUT to https://api.spotify.com/v1/me/player/play?device_id=0a4b952cd7e4134dd459d5f41007a513 with Params: {} returned 404 due to Not found.















This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/spotcast/spotcast_controller.py:315
Integration: Spotcast (documentation, issues)
First occurred: 21:32:22 (1 occurrences)
Last logged: 21:32:22

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=0a4b952cd7e4134dd459d5f41007a513: Not found., reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play?device_id=0a4b952cd7e4134dd459d5f41007a513

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 254, in start_casting
    spotcast_controller.play(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 315, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1776, in start_playback
    return self._put(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 312, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=0a4b952cd7e4134dd459d5f41007a513:
 Not found., reason: None












Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:315
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:32:22 (1 occurrences)
Last logged: 21:32:22

[546723275504] Error handling message: Unknown error (unknown_error) from 192.168.0.4 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play?device_id=0a4b952cd7e4134dd459d5f41007a513

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 254, in start_casting
    spotcast_controller.play(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 315, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1776, in start_playback
    return self._put(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 312, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=0a4b952cd7e4134dd459d5f41007a513:
 Not found., reason: None
















This error originated from a custom integration.

Logger: custom_components.spotcast.spotcast_controller
Source: custom_components/spotcast/spotcast_controller.py:242
Integration: Spotcast (documentation, issues)
First occurred: 21:25:20 (12 occurrences)
Last logged: 21:32:34

No device with id "0a4b952cd7e4134dd459d5f41007a513" known by Spotify
Known devices: [{'id': 'fd4e583bd92d073af2418a0f1dbbba7f5e34b55f', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'Web Player (Chrome)', 'type': 'Computer', 'volume_percent': 25}]
````

**Comment by hmmbob** [comment]
You've removed the complete issue template, which asks a whole bunch of questions that helps us helping you. With just dropping your logs here, there isn't much we can do.
