### ISSUE TITLE
Device not known to Spotify (when waking up)

### ISSUE THREAD

**Issue by qdrop17** [fondberg/spotcast#384]
# Bug Ticket

## Describe the bug

I try to setup an alarm using Spotcast to start a stream of my favorite playlist in the morning. For that I created an automation. I'm not able to start the Spotify stream in the morning. When triggering the automation manually in the morning, the stream starts to play properly.

The logs indicate somehow, that Spotify is not recognizing the playing device properly. Furthermore I don't unterstand how to process differs when streaming via Chromecast in comparison to Spotify connect. Well I understand the difference but it seems it relies on Spotify connect - no matter how I configure Spotcast.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

- [x] Using latest version of spotcast (deployed using docker-compose, latest-tag and watchtower)
- [x] Using latest stable version of Home Assistant (deployed using docker-compose, latest-tag and watchtower)
- [x] I have setup the Spotify integration in Home Assistant
- [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
- [x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
- [x] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
- [x] (optional) I'm using entity_id in the service call
* [x] and have tried device_name but the issue remains.

## Environment

 - Installation type: (deployed using docker-compose, latest-tag and watchtower)
 - HA version: 2023.3.3 / Frontend 20230309.0 - latest
 - spotcast version: v3.7.0, pulled from this repo

## Configuration

````
# Enable Spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: CH
````
This configuration works as I'm able to us Spotcast when triggered manually.

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

```
alias: Play Radio
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.wecker_schedule
    from: "off"
    to: "on"
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id: media_player.qdrop_shield
  - service: spotcast.start
    data:
      limit: 20
      random_song: true
      shuffle: true
      ignore_fully_played: false
      force_playback: true
      start_volume: 0
      uri: spotify:playlist:37i9dQZF1DX6KItbiYYmAv
      repeat: "off"
      offset: 0
      entity_id: media_player.qdrop_shield
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: spotcast.start
    data:
      limit: 20
      random_song: true
      shuffle: true
      ignore_fully_played: false
      force_playback: true
      start_volume: 40
      uri: spotify:playlist:37i9dQZF1DX6KItbiYYmAv
      repeat: "off"
      offset: 0
      entity_id: media_player.qdrop_shield
mode: single
```

Note, that I trigger the spotcast.start twice as I use the first one to wake up my Chromecast. This behaves the same from the smartphone: Streaming on first try fails, on second try it works.

## Logs

```
2023-03-10 07:00:00.002 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Running automation actions
2023-03-10 07:00:00.002 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step call service
2023-03-10 07:00:00.005 INFO (SyncWorker_4) [pychromecast.controllers] Receiver:setting volume to 0.4
2023-03-10 07:00:00.006 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Skipped disabled step call_service
2023-03-10 07:00:00.007 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step call service
2023-03-10 07:00:00.009 DEBUG (SyncWorker_3) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-10 07:00:00.220 DEBUG (SyncWorker_3) [custom_components.spotcast.spotcast_controller] expires: 1678431300 time: 1678428000.2201397
2023-03-10 07:00:00.220 DEBUG (SyncWorker_3) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-10 07:00:00.368 DEBUG (SyncWorker_3) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_qdrop17: None: []
2023-03-10 07:00:00.444 DEBUG (SyncWorker_3) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:00.445 DEBUG (SyncWorker_3) [custom_components.spotcast.helpers] get_cast_devices: media_player.qdrop_shield: None cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)
2023-03-10 07:00:00.446 DEBUG (SyncWorker_3) [custom_components.spotcast.spotcast_controller] Chromecast devices: [ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)]
2023-03-10 07:00:00.446 DEBUG (SyncWorker_3) [custom_components.spotcast.spotcast_controller] cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)
2023-03-10 07:00:00.446 DEBUG (SyncWorker_3) [custom_components.spotcast.spotcast_controller] Found cast device: Chromecast('unknown', port=8009, cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'))
2023-03-10 07:00:00.557 INFO (SyncWorker_3) [pychromecast.controllers] Receiver:Launching app CC32E753
2023-03-10 07:00:10.011 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step delay 0:00:10
2023-03-10 07:00:11.559 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01GV51NKR1QYSBD3K7MSEZJ3DJ): limit=20, random_song=True, shuffle=True, ignore_fully_played=False, force_playback=True, start_volume=0, uri=spotify:playlist:37i9dQZF1DX6KItbiYYmAv, repeat=off, offset=0, entity_id=media_player.qdrop_shield>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1851, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 250, in get_spotify_device_id
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 95, in startSpotifyController
    sp.launch_app()
  File "/config/custom_components/spotcast/spotify_controller.py", line 104, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
2023-03-10 07:00:20.012 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step call service
2023-03-10 07:00:20.014 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-10 07:00:20.014 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] expires: 1678431300 time: 1678428020.0143847
2023-03-10 07:00:20.014 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-10 07:00:20.269 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_qdrop17: None: []
2023-03-10 07:00:20.321 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:20.321 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_cast_devices: media_player.qdrop_shield: None cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)
2023-03-10 07:00:20.321 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] Chromecast devices: [ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)]
2023-03-10 07:00:20.321 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)
2023-03-10 07:00:20.322 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] Found cast device: Chromecast('unknown', port=8009, cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'))
2023-03-10 07:00:20.486 INFO (SyncWorker_2) [pychromecast.controllers] Not launching app CC32E753 - already running
2023-03-10 07:00:20.898 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_qdrop17: None: []
2023-03-10 07:00:20.898 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] Searching for Spotify device: 8ccde1ae4f64690dfc021263fd2df616
2023-03-10 07:00:20.974 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:22.035 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:23.801 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:26.637 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:31.434 DEBUG (SyncWorker_2) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-10 07:00:37.281 ERROR (SyncWorker_2) [custom_components.spotcast.spotcast_controller] No device with id "8ccde1ae4f64690dfc021263fd2df616" known by Spotify
2023-03-10 07:00:37.282 ERROR (SyncWorker_2) [custom_components.spotcast.spotcast_controller] Known devices: []
2023-03-10 07:00:37.282 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01GV51NKR1QYSBD3K7MSEZJ3DJ): limit=20, random_song=True, shuffle=True, ignore_fully_played=False, force_playback=True, start_volume=40, uri=spotify:playlist:37i9dQZF1DX6KItbiYYmAv, repeat=off, offset=0, entity_id=media_player.qdrop_shield>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1851, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 252, in get_spotify_device_id
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(me_resp["id"])
  File "/config/custom_components/spotcast/spotcast_controller.py", line 134, in getSpotifyDeviceId
    raise HomeAssistantError("Failed to get device id from Spotify")
homeassistant.exceptions.HomeAssistantError: Failed to get device id from Spotify
```

When checking out the logs, I can see that despite choosing Chromecast as protocol, Spotify somehow does not find the respective device.

The strange thing is, that when I wake up in the morning without music, I can trigger the automation manually in HA and the music will start playing. Is there some strange timeout to wait before the devices are available in Spotify?

For reference, these are the logs when triggering manually:

```
2023-03-13 08:28:58.564 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Running automation actions
2023-03-13 08:28:58.564 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step call service
2023-03-13 08:28:58.565 INFO (SyncWorker_2) [pychromecast.controllers] Receiver:setting volume to 0.4
2023-03-13 08:28:58.567 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step call service
2023-03-13 08:28:58.568 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-13 08:28:58.700 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] expires: 1678695838 time: 1678692538.7008312
2023-03-13 08:28:58.701 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-13 08:28:58.827 DEBUG (SyncWorker_0) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_qdrop17: None: []
2023-03-13 08:28:58.887 DEBUG (SyncWorker_0) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': []}
2023-03-13 08:28:58.888 DEBUG (SyncWorker_0) [custom_components.spotcast.helpers] get_cast_devices: media_player.qdrop_shield: None cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)
2023-03-13 08:28:58.888 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Chromecast devices: [ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)]
2023-03-13 08:28:58.888 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'), is_dynamic_group=None)
2023-03-13 08:28:58.889 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Found cast device: Chromecast('unknown', port=8009, cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.7.12', 8009))}, uuid=UUID('9cd1b2e7-d156-43fc-82f0-7847f9528d05'), model_name='SHIELD Android TV', friendly_name='qdrop-shield', host='192.168.7.12', port=8009, cast_type='cast', manufacturer='NVIDIA'))
2023-03-13 08:28:58.987 INFO (SyncWorker_0) [pychromecast.controllers] Receiver:Launching app CC32E753
2023-03-13 08:29:02.850 DEBUG (SyncWorker_0) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_qdrop17: None: []
2023-03-13 08:29:02.850 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Searching for Spotify device: 8ccde1ae4f64690dfc021263fd2df616
2023-03-13 08:29:02.912 DEBUG (SyncWorker_0) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': [{'id': '8ccde1ae4f64690dfc021263fd2df616', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'qdrop-shield', 'type': 'CastVideo', 'volume_percent': 40}]}
2023-03-13 08:29:02.912 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Found matching Spotify device: {'id': '8ccde1ae4f64690dfc021263fd2df616', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'qdrop-shield', 'type': 'CastVideo', 'volume_percent': 40}
2023-03-13 08:29:02.914 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Playing URI: spotify:playlist:37i9dQZF1DX6KItbiYYmAv on device-id: 8ccde1ae4f64690dfc021263fd2df616
2023-03-13 08:29:03.301 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Start playback at random position: 15
2023-03-13 08:29:03.301 DEBUG (SyncWorker_0) [custom_components.spotcast.spotcast_controller] Playing context uri using context_uri for uri: "spotify:playlist:37i9dQZF1DX6KItbiYYmAv" (random_song: True)
2023-03-13 08:29:03.528 DEBUG (SyncWorker_0) [custom_components.spotcast] Setting volume to 0
2023-03-13 08:29:05.601 DEBUG (SyncWorker_0) [custom_components.spotcast] Turning shuffle on
2023-03-13 08:29:08.569 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step delay 0:00:10
2023-03-13 08:29:08.794 DEBUG (SyncWorker_0) [custom_components.spotcast] Turning repeat on
2023-03-13 08:29:18.570 INFO (MainThread) [homeassistant.components.automation.play_discover_weekly] Play Radio: Executing step call service
2023-03-13 08:29:18.571 DEBUG (SyncWorker_1) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-13 08:29:18.572 DEBUG (SyncWorker_1) [custom_components.spotcast.spotcast_controller] expires: 1678695838 time: 1678692558.5719924
2023-03-13 08:29:18.572 DEBUG (SyncWorker_1) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-03-13 08:29:18.686 DEBUG (SyncWorker_1) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_qdrop17: None: []
2023-03-13 08:29:18.741 DEBUG (SyncWorker_1) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': [{'id': '8ccde1ae4f64690dfc021263fd2df616', 'is_active': True, 'is_private_session': False, 'is_restricted': False, 'name': 'qdrop-shield', 'type': 'CastVideo', 'volume_percent': 0}]}
2023-03-13 08:29:18.743 DEBUG (SyncWorker_1) [custom_components.spotcast.spotcast_controller] Playing URI: spotify:playlist:37i9dQZF1DX6KItbiYYmAv on device-id: 8ccde1ae4f64690dfc021263fd2df616
2023-03-13 08:29:18.988 DEBUG (SyncWorker_1) [custom_components.spotcast.spotcast_controller] Start playback at random position: 120
2023-03-13 08:29:18.988 DEBUG (SyncWorker_1) [custom_components.spotcast.spotcast_controller] Playing context uri using context_uri for uri: "spotify:playlist:37i9dQZF1DX6KItbiYYmAv" (random_song: True)
2023-03-13 08:29:19.241 DEBUG (SyncWorker_1) [custom_components.spotcast] Setting volume to 40
2023-03-13 08:29:21.414 DEBUG (SyncWorker_1) [custom_components.spotcast] Turning shuffle on
2023-03-13 08:29:24.573 DEBUG (SyncWorker_1) [custom_components.spotcast] Turning repeat on
```

Any help is highly appreciated.

**Comment by fcusson** [comment]
@qdrop17 why do a lot of people that open tickets feel the need to remove part of the bug report template?

You removed questions from it that are critical for us to start help you.

Please edit your bug report following [the bug report](https://github.com/fondberg/spotcast/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

Without the details regarding your installation, mainly versions, we can't even start troubleshooting. Please also follow the templates section to organize your ticket has it makes it much easier for us to go through the tickets details while debug your case.

**Comment by qdrop17** [comment]
> @qdrop17 why do a lot of people that open tickets feel the need to remove part of the bug report template?
> 
> You removed questions from it that are critical for us to start help you.
> 
> Please edit your bug report following [the bug report](https://github.com/fondberg/spotcast/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
> 
> Without the details regarding your installation, mainly versions, we can't even start troubleshooting. Please also follow the templates section to organize your ticket has it makes it much easier for us to go through the tickets details while debug your case.

ok, I updated the request. I understand that these parameters were missing in my initial request - sorry,

**Comment by fcusson** [comment]
hi @qdrop17,

to answer your questions:

> it seems it relies on Spotify connect - no matter how I configure Spotcast.

That's the way it works. Spotify interacts purely with it's Spotify Connect protocol. Chromecast is just a layer for google devices to manage media playback.

The problem could be that the device is not ready when you they media playback request is done. Do you have a way in your automation to start the nvidia shield before making the request? I would recommend an automation that ensure's the nvidia shield is properly ready before starting the media playback.

Also, when the problem happen, what is the state of the device and is it possible to see the device in the list of [spotify connect device](https://developer.spotify.com/console/get-users-available-devices/)?

**Comment by qdrop17** [comment]
Well I reconfigured my automation to try to start the stream twice, then waiting for 1 minute and trying it again. Now it works. It seems that Spotify connect takes some time to get ready.

We can close this issue; I don't think it has to do with Spotcast.

Thank you for your support anyways.

**Comment by fcusson** [comment]
Just for sake of improvements, you could also make a `wait_for_trigger` and check for a state or attribute in your nvidia shield that is only available while fully on and not there while sleeping or off. That could decrease false negative where you are waiting more than needed and also false positive where it believe it is ready after a minute and will just fail again.
