### ISSUE TITLE
Errors every day

### ISSUE THREAD

**Issue by mfabiani53** [fondberg/spotcast#388]
Every day i get these errors in the log:

```
2023-03-22 07:00:08.782 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.playlists_sensor fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/playlists?limit=40&offset=0 (Caused by ResponseError('too many 502 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 264, in _internal_call
    response = self._session.request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/playlists?limit=40&offset=0 (Caused by ResponseError('too many 502 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 116, in update
    resp = self.hass.data[DOMAIN]["controller"].get_playlists(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 333, in get_playlists
    resp = client.current_user_playlists(limit=limit)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 635, in current_user_playlists
    return self._get("me/playlists", limit=limit, offset=offset)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 321, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 305, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/me/playlists?limit=40&offset=0:
 Max Retries, reason: too many 502 error responses
```
Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x ] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x ] I have setup the Spotify integration in Home Assistant
* [x ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x ] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [2022.3.5 ]
 - spotcast version: [latest ]

**Comment by fcusson** [comment]
@mfabiani53, the weird thing is 502 is a server side error. That should mean that Spotify experiencing issues, but that wouldn't make sense if you are the only one with the problem.

Are you using any unconventional networking gear like personal DNS (pihole, adguard) are using any network wide VPN?

**Comment by mfabiani53** [comment]
Not at all... no unconventional networking.
You mean i am not the only one with this problem?

**Comment by fcusson** [comment]
> You mean i am not the only one with this problem?

Technically you are not at fault based on the error code (anything >=500 is server side error), but Spotify could be giving bad error codes or you could be triggering an edge case they didn't expect.

> I changed in sensor.py file the limit of the playlists to 40 and the language to 'it'. Could this be in some way the cause of the error?

That would have been a very good information to have from the start. Can you provide me your modified version of the sensor.py file. Also I would need your configuration for spotcast. If you hardcoded your sp_dc and sp_key, first anonymise then and please use !secret.

**Comment by mfabiani53** [comment]
This is modified version of sensor.py:

```
"""Sensor platform for Chromecast devices."""
from __future__ import annotations

import collections
import json
import logging
from datetime import timedelta
import homeassistant.core as ha_core

from homeassistant.components.sensor import SensorEntity
from homeassistant.const import STATE_OK, STATE_UNKNOWN
from homeassistant.util import dt

from .helpers import get_cast_devices
from .const import (
    DOMAIN,
    CONF_SPOTIFY_COUNTRY
)

_LOGGER = logging.getLogger(__name__)

SENSOR_SCAN_INTERVAL_SECS = 60
SCAN_INTERVAL = timedelta(seconds=SENSOR_SCAN_INTERVAL_SECS)


def setup_platform(hass:ha_core.HomeAssistant, config:collections.OrderedDict, add_devices, discovery_info=None):

    try:
        country = config[CONF_SPOTIFY_COUNTRY]
    except KeyError:
        country = None

    add_devices([ChromecastDevicesSensor(hass)])
    add_devices([ChromecastPlaylistSensor(hass, country)])


class ChromecastDevicesSensor(SensorEntity):
    def __init__(self, hass):
        self.hass = hass
        self._state = STATE_UNKNOWN
        self._chromecast_devices = []
        self._attributes = {"devices_json": [], "devices": [], "last_update": None}
        _LOGGER.debug("initiating sensor")

    @property
    def name(self):
        return "Chromecast Devices"

    @property
    def state(self):
        return self._state

    @property
    def extra_state_attributes(self):
        """Return the state attributes."""
        return self._attributes

    def update(self):
        _LOGGER.debug("Getting chromecast devices")

        known_devices = get_cast_devices(self.hass)
        _LOGGER.debug("sensor devices %s", known_devices)

        chromecasts = [
            {
                "uuid": str(cast_info.cast_info.uuid),
                "model_name": cast_info.cast_info.model_name,
                "name": cast_info.cast_info.friendly_name,
                "manufacturer": cast_info.cast_info.manufacturer,
                "cast_type": cast_info.cast_info.cast_type,
            }
            for cast_info in known_devices
        ]

        self._attributes["devices_json"] = json.dumps(chromecasts, ensure_ascii=False)
        self._attributes["devices"] = chromecasts
        self._attributes["last_update"] = dt.now().isoformat("T")
        self._state = STATE_OK


class ChromecastPlaylistSensor(SensorEntity):
    def __init__(self, hass: ha_core, country=None):
        self.hass = hass
        self._state = STATE_UNKNOWN
        self.country = country
        self._attributes = {"playlists": [], "last_update": None}
        _LOGGER.debug("initiating playlist sensor")

    @property
    def name(self):
        return "Playlists sensor"

    @property
    def state(self):
        return self._state

    @property
    def extra_state_attributes(self):
        """Return the state attributes."""
        return self._attributes

    def update(self):
        _LOGGER.debug("Getting playlists")

        if self.country is not None:
            country_code = self.country
        else:
            # kept the country code to SE if not provided by the user for retrocompatibility
            country_code = "SE"

        playlist_type = "user"
        locale = "it"
        limit = 40
        account = None

        resp = self.hass.data[DOMAIN]["controller"].get_playlists(
            account, playlist_type, country_code, locale, limit
        )
        self._attributes["playlists"] = [{ "uri": x['uri'], "name": x['name']} for x in resp['items'] ]

        self._attributes["last_update"] = dt.now().isoformat("T")
        self._state = STATE_OK
```

And this my config about spotcast:

```
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: IT
```

**Comment by fcusson** [comment]
I tested on my end and the new limit doesn't affect the calls. As predicted, the limit Spotify has is 50 and when you go over the error is 403 `unauthorized`, not 504 which is a `timeout error`.

I dug

**Comment by mfabiani53** [comment]
What you mean with this:

```
 your are busting the rate limit of Spotify API
```
 About requests, you mean this:
![Schermata 2023-03-25 alle 16 47 41](https://user-images.githubusercontent.com/37701688/227727713-14c28bd6-33c1-484d-9187-c660a86a386f.png)

```
Also make sure that your monthly active user makes sense
```
![Schermata 2023-03-25 alle 16 49 06](https://user-images.githubusercontent.com/37701688/227727778-7fb6a627-63ff-4efd-a883-e2fde8e56122.png)

**Comment by fcusson** [comment]
> What you mean with this:
> > your are busting the rate limit of Spotify API

All API have rate limits they don't want a script kitty who thiks he's a hacker send a bunch a distributed queries and clog the API endpoint fro 4chans points. 

You can read more on the rate limit [here](https://developer.spotify.com/documentation/web-api/guides/rate-limits/), but with the number of queries you have I doubt that you have a generally busy api query rate. You seems to have more of a burst problem, basically you have rolling 30 sec. of number of queries and if your rolling sum of queries go over the limit you get a 429 error.

Before we get stuck in a circle for no reasong. Could you revert the changes you made in the `sensor.py` to verify if it resolves the problem or not? At least we'll know if it is the cause.

**Comment by mfabiani53** [comment]
Ok, i'll let you know...

**Comment by mfabiani53** [comment]
I switched back to the default values, but this morning i got the same errors as before:

```
2023-03-27 07:00:14.658 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.playlists_sensor fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/playlists?limit=10&offset=0 (Caused by ResponseError('too many 502 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 264, in _internal_call
    response = self._session.request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/playlists?limit=10&offset=0 (Caused by ResponseError('too many 502 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 116, in update
    resp = self.hass.data[DOMAIN]["controller"].get_playlists(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 333, in get_playlists
    resp = client.current_user_playlists(limit=limit)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 635, in current_user_playlists
    return self._get("me/playlists", limit=limit, offset=offset)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 321, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 305, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/me/playlists?limit=10&offset=0:
```

**Comment by mfabiani53** [comment]
FYI after some hours of default sensor.py worked, the errors are not anymore in the log. So, i think, the errors lie in the modified sensor.py.

**Comment by fcusson** [comment]
Ok good to k kw. I wanted to give you an update but had a crazy week at work.

I did some documentation reading and the playlists API is on a different rate limit than the rest of the api. The problem is they don't say what it is.

I have a feeling it is based on the number of playlist fetched and not calls. Would explain the problem with your 429 error. This is still a guess at the moment.

**Comment by mfabiani53** [comment]
Ok  i'll stay tuned....
But.... sad to say... this morning the errors came up again... always at the same hour as previously...

**Comment by fcusson** [comment]
The problem seems to be specific to some regions. I did some research online and some developpers are stuck with always receiving 502 errors while others don't. Can you verify from your side if [this endpoint](https://developer.spotify.com/documentation/web-api/reference/get-a-list-of-current-users-playlists) works in the developper console?

**Comment by fcusson** [comment]
`V5` handles sensors very differently and should no longer break on 502 error. This should improve the experience a lot.

**Comment by Mincka** [comment]
This one showed twice in a row today with [v5.0.0-b32](https://github.com/fondberg/spotcast/releases/tag/v5.0.0-b32).
Not tested on b33 yet.

```
2025-03-20 17:08:48.673 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.spotcast_xxx_spotify_liked_songs fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 897, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<11 lines>...
        **response_kw
        ^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 897, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<11 lines>...
        **response_kw
        ^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 897, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<11 lines>...
        **response_kw
        ^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 887, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=1&offset=0 (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/spotipy/client.py", line 266, in _internal_call
    response = self._session.request(
        method, url, headers=headers, proxies=self.proxies,
        timeout=self.requests_timeout, **args
    )
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/tracks?limit=1&offset=0 (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/spotcast/sensor/abstract_entity.py", line 164, in async_update
    await self._async_update_process()
  File "/config/custom_components/spotcast/sensor/spotify_liked_songs_sensor.py", line 32, in _async_update_process
    count = await self.account.async_liked_songs_count()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotify/account.py", line 934, in async_liked_songs_count
    return await self._async_get_count(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.apis["private"].current_user_saved_tracks,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/spotcast/spotify/account.py", line 1181, in _async_get_count
    result = await self.hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
```

**Comment by Mincka** [comment]
Great! Thank you. 👍

**Comment by fcusson** [comment]
build 34 released

**Comment by ParksideParade** [comment]
I'm also getting this error constantly - 734 occurrences. Any tips?

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:955
First occurred: March 13, 2026 at 9:56:13 PM (734 occurrences)
Last logged: 10:09:14 AM

Update for sensor.playlists_sensor fails
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 174, in get_spotify_token
    ).result()
      ~~~~~~^^
  File "/usr/local/lib/python3.14/concurrent/futures/_base.py", line 450, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/concurrent/futures/_base.py", line 395, in __get_result
    raise self._exception
  File "/config/custom_components/spotcast/spotcast_controller.py", line 210, in start_session
    server_time = data["serverTime"]
                  ~~~~^^^^^^^^^^^^^^
KeyError: 'serverTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1329, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 118, in update
    resp = self.hass.data[DOMAIN]["controller"].get_playlists(
        account, playlist_type, country_code, locale, limit
    )
  File "/config/custom_components/spotcast/spotcast_controller.py", line 453, in get_playlists
    client = self.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 324, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 166, in access_token
    self.ensure_token_valid()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 162, in ensure_token_valid
    self.get_spotify_token()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 184, in get_spotify_token
    raise HomeAssistantError(exc)
homeassistant.exceptions.HomeAssistantError: 'serverTime'`
