### ISSUE TITLE
Cannot find device with name ...

### ISSUE THREAD

**Issue by watermarkhu** [fondberg/spotcast#39]
Hi, Spotcast is failing to work for me for some time now. I cannot start playback with when calling the service.  The media_player entity itself is working properly and it even shows up in the _Spotify Playlist Player_.

![image](https://user-images.githubusercontent.com/18556882/69664225-3a6c6380-1088-11ea-92c5-53bc98993498.png)
```
Could not find device with name Google Home Mini
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1263, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 155, in start_casting
    cast = get_chromecast_device(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 82, in get_chromecast_device
    raise HomeAssistantError('Could not find device with name {}'.format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Google Home Mini
Could not find device Google Home Mini from hass.data, falling back to pychromecast scan
```

**Comment by watermarkhu** [comment]
Full restart of pull (not just HA) fixed this.
