### ISSUE TITLE
After trying to play some particular songs, nothing happens, and no other Spotify content can be played

### ISSUE THREAD

**Issue by V69dxz** [fondberg/spotcast#397]
# Bug Ticket

## Describe the bug
Thank you for this integration!

After clicking certain particular songs or playlists on Spotify in the mediaplayer, Spotcast crashes (?) and I am unable to select and play other songs and playlists. When I restart Home Assistant everything works again as expected. (NB. I also had this error once after I tried to play a radio station from the radio integration that was no longer available / IP address was unavailable).  

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

[x ] Using latest version of spotcast
[x ] Using latest stable version of Home Assistant
[x ] I have setup the Spotify integration in Home Assistant
[ x ] I have renewed my sp_dc and sp_key values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
[ x] (optional) I have Spotify Premium
 (optional) I am using multiple accounts
 (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
 (optional) I'm using entity_id in the service call and have tried device_name but the issue remains
Environment

Installation type: [HA_OS|Container|Supervised|Core]
HA version: [2023.7 ]

## Logs

* normal|debug

````log
No new error logs seem to be created after a crash.

<Logger: homeassistant.core
Source: custom_components/spotcast/spotify_controller.py:104 
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues)) 
First occurred: 18:27:31 (1 occurrences) 
Last logged: 18:27:31

Error executing service: <ServiceCall spotcast.start (c:01H5Z6TV9F9R8VMM0NMTQTNM2V): entity_id=media_player.nest_mini_room, uri=spotify:track:3NFnEfVZrBP2ergaV6zibG, random_song=False, start_volume=101, limit=20, repeat=off, force_playback=False, shuffle=False, offset=0, ignore_fully_played=False>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1983, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2013, in _execute_service
    return await self._hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 250, in get_spotify_device_id
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 95, in startSpotifyController
    sp.launch_app()
  File "/config/custom_components/spotcast/spotify_controller.py", line 104, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app>
````

## Additional context

<Add any other context about the problem here.>

**Comment by easterapps** [comment]
Hi, i had a similar issue. Please check the keys (sp_key and sp_dc) and also check the app in spotify developer.

**Comment by pmkruyen** [comment]
Ok, thanks. Good suggestions. I will double check the app in Spotify developer. (I already renewed the key and dc.)

**Comment by oshriphoto** [comment]
It seems that this is a problem that appears to many users, does anyone have a solution to this problem? Is the developer of the plugin in the group and reading the errors? Maybe he can respond and say if it is in treatment or not?

**Comment by pmkruyen** [comment]
I confirm that I still have this problem.

A working hypothesis: does this happen when/after I open my Spotify account on another device confusing Spotify?

**Comment by fcusson** [comment]
@pmkruyen, @easterapps, @oshriphoto has anyone been able to test with the new beta if this issue is resolved. I implemented a much better way handling closing and opening the Spotify app on Chromecast in this iteration

**Comment by michi1g** [comment]
I was running into the same issue. Tried the latest beta and it is working now

**Comment by V69dxz** [comment]
Hi all! Thanks for all the work!


Sorry...  I'm back :) We use this integration quite a lot and I have been so accustomed to reset HA to deal with this issue that I forgot to look for a structural solution. Also, we started to use the Music Assistant add on as alternative music source which hasnt' has these issues, but comes with other problems in our set up.

Anyway. I'm happy to test the beta integration @fcusson . Have to figure out how to download it :)

**Comment by V69dxz** [comment]
Sorry I cannot get pass the OA verification.
- I deleted everything from the old spotcast integration from the configuration yalm 
- I created a new spotify app on the developer portal
- I installed v. 5.0.0
- When I click on install I am directed to another page to link the account but next I get an empty screen (I remember from setting up this account for the spotify integration + Music Assistant I am redirected to my spotify account to grant all permissions to the app).
- Next, when I manually return to my HA page, I see a pop up window in which I can answer my cookie credentials (sp); but next I get an 'unknown error'.

- In one of the attempts I shortly saw an error message that I try to link different accounts.

Happy to provide more info if needed + guess I should put into another issue.

**Comment by fcusson** [comment]
> When I click on install I am directed to another page to link the account but next I get an empty screen (I remember from setting up this account for the spotify integration + Music Assistant I am redirected to my spotify account to grant all permissions to the app).

That part is normal if you are using the same spotify application, you only need to provide approval once per application, we are just fetching a new set of oauth token for spotcast

**Comment by V69dxz** [comment]
👋👍👍Op 30 jan 2025 om 01:58 heeft Felix Cusson ***@***.***> het volgende geschreven:﻿
@V69dxz, please open a new ticket. I'll need more details, you should have an error log when you get the unknown error, please provide that in your diagnostic information

**Comment by V69dxz** [comment]
Ok! I'm ready to test...
- deleted version 4.0.0 of the integration
- removed the `spotcast `lines from the yalm configuration 
- restored HA
- downloaded the developer version of spotcast
- restarted HA
- logged in to our main spotify account, for which I also have a developer account
- added the spodcast integration; 
- and filled out the sp_key and sp_dc

**Comment by V69dxz** [comment]
With version 5 the problem no longer exists, indeed. Thank you!
