### ISSUE TITLE
Spotcast is not working

### ISSUE THREAD

**Issue by jorgeelima** [fondberg/spotcast#401]
# Bug Ticket

## Describe the bug

Spotcast service os not working upon launch 

Logs
[Office(192.168.1.64):8009] Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from 22f4ae1c-837e-4f13-a274-74626fdc5e24 to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Google_Home', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb71494ea994202cb473eae7', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
[Office(192.168.1.64):8009] Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from 05bbd739-30cf-4a7a-8d98-2d64ee1025c2 to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Google_Home', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb71494ea994202cb473eae7', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py", line 719, in _route_message
    handled = handler.receive_message(message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotify_controller.py", line 47, in receive_message
    self.device = data["payload"]["deviceID"]

**Comment by antonio1475** [comment]
Duplicate of https://github.com/fondberg/spotcast/issues/398 ?
