### ISSUE TITLE
NameError: name 'HomeAssistantSpotifyData' is not defined

### ISSUE THREAD

**Issue by barzag** [fondberg/spotcast#444]
# Bug Ticket

## Describe the bug

Hello, when I try to launch a playlist via Spotify using Spotcast, I receive the following error message:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1308, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 654, in async_browse_media
    browse_media = await platform.async_browse_media(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/cast.py", line 47, in async_browse_media
    result = await ha_spotify.async_browse_media(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/spotify/browse_media.py", line 181, in async_browse_media
    or not isinstance(entry.runtime_data, HomeAssistantSpotifyData)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'HomeAssistantSpotifyData' is not defined
```

I haven't changed any configurations. The problem appeared suddenly.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [X] Using latest version of spotcast
* [X] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [X] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ 2024.6.1]
 - spotcast version: [ latest]

## Configuration

````yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: CH #optional, added in 3.6.24

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1308, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 654, in async_browse_media
    browse_media = await platform.async_browse_media(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/cast.py", line 47, in async_browse_media
    result = await ha_spotify.async_browse_media(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/spotify/browse_media.py", line 181, in async_browse_media
    or not isinstance(entry.runtime_data, HomeAssistantSpotifyData)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'HomeAssistantSpotifyData' is not defined

````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by barzag** [comment]
No body ?

**Comment by fcusson** [comment]
@barzag the bug is comming from the official spotify integration, not spotcast, please open a ticket with them
