### ISSUE TITLE
Latest update breaks Spotify Card?

### ISSUE THREAD

**Issue by joq3** [fondberg/spotcast#461]
After updating to spotcast 3.8.2 the spotify-card broke: https://github.com/custom-cards/spotify-card
From what I understand it is the same creator, which is no longer with us, and there is no support or maintainer on the spotify-card.

Is it possible to adjust spotcast integration to not break spotify-card or does this have to be fixed in the spotify-card?

**Comment by Pirol62** [comment]
Yes, same here

**Comment by PerSterin** [comment]
If you have this error, change line 146 of init.py. and restart HA. See error in logger below.

From: resp = get_spotify_devices(spotify_media_player)
To: resp = get_spotify_devices(spotify_media_player, hass)

This solved my problem

Logger: homeassistant
Source: custom_components/spotcast/init.py:146
integration: Spotcast (documentation, issues)
First occurred: 15:38:48 (4 occurrences)
Last logged: 15:39:16

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/config/custom_components/spotcast/helpers.py", line 122, in run
return await loop.run_in_executor(executor, pfunc)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/init.py", line 146, in get_devices
resp = get_spotify_devices(spotify_media_player)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_spotify_devices() missing 1 required positional argument: 'hass'

**Comment by geoffoxholm** [comment]
the line in question:

https://github.com/fondberg/spotcast/blob/cb2f905a6c62022b4a97a0f611026c409e661e3f/custom_components/spotcast/__init__.py#L146

is clearly broken, as it's imported from here:

https://github.com/fondberg/spotcast/blob/cb2f905a6c62022b4a97a0f611026c409e661e3f/custom_components/spotcast/helpers.py#L60

**Comment by geoffoxholm** [comment]
Opened PR #462 to address this.

**Comment by PerSterin** [comment]
@geoffoxholm 
Yup, probably, I haven't looked at what was changed in between
 3.8.1 → 3.8.2
Great then we will get a new Spotcast release soon.
