### ISSUE TITLE
Can not play anything on Chromecast with Google TV

### ISSUE THREAD

**Issue by Gecko-with-a-hat** [fondberg/spotcast#463]
# Bug Ticket

## Describe the bug

Can not play media on google chromecast. 

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [X] Using latest version of spotcast
* [X] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [X] (optional) I have Spotify Premium
* [X] (optional) I am using multiple accounts
* [X] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [2024.10.1]
 - spotcast version: [3.8.2]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.spotcast: debug

# Reverse proxy settings
http:
  use_x_forwarded_for: true
  cors_allowed_origins: https://home.mydomain.com
  trusted_proxies:
  - 10.0.0.0/8

# Spotcast single account
#spotcast:
#  sp_dc: !secret sp_dc
#  sp_key: !secret sp_key
#  country: NL

# Spotcast multiple accounts  
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  country: $country
  accounts:
    secondary:
      sp_dc: !secret secondary_sp_dc
      sp_key: !secret secondary_sp_key

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

I use the "Media" section on the HA web UI. I select my "Living Room TV - GoogleCast" and I choose a song or playlist to play. No matter what song or playlist (on either accoutns) I pick. It just does nothing. The Media section itself works because I can play songs from my plex library on my tv here and even do the TTS messages just fine.

## Logs

* debug

````log
2024-10-09 16:47:38.282 DEBUG (MainThread) [custom_components.spotcast.cast] async_browse_media spotify://track, spotify://77d0b72a7abcaff87ae2facf16fa30b0/spotify:track:0qxYx4F3vm1AOnfux6dDxP
2024-10-09 16:47:38.284 DEBUG (SyncWorker_18) [custom_components.spotcast.spotcast_controller] setting up with  account default
2024-10-09 16:47:38.284 DEBUG (SyncWorker_18) [custom_components.spotcast.spotcast_controller] expires: 1728485379 time: 1728485258.2843025
2024-10-09 16:47:38.542 DEBUG (SyncWorker_18) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_<NAME>: None: [{'id': '<ID 1>', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'Living Room TV', 'supports_volume': True, 'type': 'TV', 'volume_percent': 100}]
2024-10-09 16:47:38.593 DEBUG (SyncWorker_18) [custom_components.spotcast.helpers] get_spotify_devices: {'devices': [{'id': '<ID 1>', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'Living Room TV', 'supports_volume': True, 'type': 'TV', 'volume_percent': 100}]}
2024-10-09 16:47:38.594 DEBUG (SyncWorker_18) [custom_components.spotcast.helpers] get_cast_devices: media_player.living_room_tv_googlecast: None cast info: ChromecastInfo(cast_info=CastInfo(services={HostServiceInfo(host='10.10.10.170', port=8009)}, uuid=UUID('<ID 2>'), model_name='Chromecast', friendly_name='Living Room TV', host='10.10.10.170', port=8009, cast_type='cast', manufacturer='Google Inc.'), is_dynamic_group=None)
2024-10-09 16:47:38.594 DEBUG (SyncWorker_18) [custom_components.spotcast.spotcast_controller] Chromecast devices: [ChromecastInfo(cast_info=CastInfo(services={HostServiceInfo(host='10.10.10.170', port=8009)}, uuid=UUID('<ID 2>'), model_name='Chromecast', friendly_name='Living Room TV', host='10.10.10.170', port=8009, cast_type='cast', manufacturer='Google Inc.'), is_dynamic_group=None)]
2024-10-09 16:47:38.594 DEBUG (SyncWorker_18) [custom_components.spotcast.spotcast_controller] cast info: None
2024-10-09 16:47:38.594 ERROR (SyncWorker_18) [custom_components.spotcast.spotcast_controller] Could not find device Living Room TV - GoogleCast from hass.data
2024-10-09 16:47:38.594 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01J9RVZX1AT7XMS383TP346DJ9): entity_id=media_player.living_room_tv_googlecast, uri=spotify:track:0qxYx4F3vm1AOnfux6dDxP, random_song=False, ignore_fully_played=False, start_volume=101, limit=20, force_playback=False, repeat=off, offset=0, shuffle=False>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2781, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2811, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 256, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 297, in get_spotify_device_id
    spotify_cast_device = SpotifyCastDevice(
                          ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 61, in __init__
    self.castDevice = self.get_chromecast_device(device_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 87, in get_chromecast_device
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Could not find device with name Living Room TV - GoogleCast
````

## Additional context

Some time ago (few months) my physical button also stopped working. I had an automation to play a specific playlist when I double pressed a physical button. The error there was that for some reason my HA could not connect to my Spotify account or something.

**Comment by fcusson** [comment]
@Gecko-with-a-hat 

The problem seem to be that you are calling the device, but your device name is not the same as in the Google Home App. Currently this is a requirement for spotcast to work properly and wake up the device.

Can you confirm if they currently have different names?

**Comment by Gecko-with-a-hat** [comment]
@fcusson 

Brilliant, completely forgot that I renamed the device. I completely missed that. Works like a charm now, thank you!

**Comment by fcusson** [comment]
@Gecko-with-a-hat glad I could help
