### ISSUE TITLE
usage of data_template in script

### ISSUE THREAD

**Issue by sverleysen** [fondberg/spotcast#47]
When I use the data_template in a script to start playing some music I get the following error message:

> [homeassistant.core] Error executing service <ServiceCall script.chromecast_spotify (c:01e0ac4fe7644f7995ab2faab6e7e8f0)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 137, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 209, in async_turn_on
    raise err
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 204, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 189, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 272, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 354, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 96, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 156, in start_casting
    spotify_cast_device = SpotifyCastDevice(hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID))
  File "/config/custom_components/spotcast/__init__.py", line 207, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 218, in getChromecastDevice
    host = str(cast_info.host)
AttributeError: 'NoneType' object has no attribute 'host'

So when I try the following script doesn't work:

>   chromecast_spotify:
    alias: Play Spotify
    sequence:
      - service: spotcast.start
        data_template:
          device_name: >
            {% if is_state("input_select.chromecast_radio", "Home Group") %} "Home group"
            {% elif is_state("input_select.chromecast_radio", "Keuken") %} "Kitchen display"
            {% elif is_state("input_select.chromecast_radio", "Living") %} "SoundBar"
            {% elif is_state("input_select.chromecast_radio", "Slaapkamer") %} "Bedroom speaker"
            {% elif is_state("input_select.chromecast_radio", "Badkamer") %} "Bathroom speaker"
            {% elif is_state("input_select.chromecast_radio", "Boven") %} "Boven"
            {% endif %}
          uri: "valid spotify uri"

When I change data_template: to data: and hard-code the device name, the music starts.

>   chromecast_spotify:
    alias: Play Spotify
    sequence:
      - service: spotcast.start
        data:
          device_name: "Home group"
          uri: "valid spotify uri"

My template is valid, when I try the template tester from HA, I receive the valid device_name with quotes.

Is data_template not supported? Or am I doing something wrong?

**Comment by fondberg** [comment]
I'm no jinja expert but I think you will send new lines with the way your template is written. 
Templates is not something a component need to support so the correct place to ask these questions would be on the forum where I know a lot of users of hass helps out. Pretty sure your exact template already exists in several places there.
I will close this as this is not a spotcast issue

**Comment by marrobHD** [comment]
@sverleysen Look at this. I got data templating working.
```
wakeup_source:
  alias: Play a Source on Google Audio
  sequence:
  - service: spotcast.start
    data_template:
      device_name: '{% if is_state("input_select.wakeup_speaker", "Schlafzimmer") %}Marlons Zimmer
                  {% elif is_state("input_select.wakeup_speaker","Off") %}Beeeep
                  {% endif %}'
      uri: '{% if is_state("input_select.wakeup_play", "Main Stage") %}spotify:playlist:37i9dQZF1DX7ZUug1ANKRP
            {% elif is_state("input_select.wakeup_play", "Electronic Rising") %}spotify:playlist:37i9dQZF1DX8AliSIsGeKd
            {% elif is_state("input_select.wakeup_play", "Off") %}donothing
            {% endif %}'
      shuffle: true
```
