### ISSUE TITLE
Not able to install spotcast after update of HA to 2024.11.0 error: no module named 'spotipy'

### ISSUE THREAD

**Issue by canedje** [fondberg/spotcast#472]
# Bug Ticket

## Describe the bug
After updat HA to 2024.11.0
I do get spotcast not setup anymore.
giving error:
![image](https://github.com/user-attachments/assets/0d49dedb-0bfb-4233-b6c5-eac87052652d)
and in the log:
![image](https://github.com/user-attachments/assets/83484e3b-f584-4d0b-949c-05e28c551083)

<A clear and concise description of what the bug is.>

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ v3.9.0] Using latest version of spotcast
* [ 2024.11.0] Using latest stable version of Home Assistant
* [not possible ] I have setup the Spotify integration in Home Assistant
* [ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [yes ] (optional) I have Spotify Premium
* [no ] (optional) I am using multiple accounts
* [yes ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container]
 - HA version: [ 2024.11.0]
 - spotcast version: [v3.9.0 ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>
spotcast:
  sp_dc: key
  sp_key: key
````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by Tom-Heitbrink** [comment]
Message not only shows up upon installation, but also upon a reboot of HA. So likely impacting all spotcast users.

**Comment by fcusson** [comment]
Hi it was requested that I remove the fix for `2024.11` because it was annoying to have an update you couldn't install. The update will come later. You can look at comments from #470  and #469.

The fix will be release once I have the time, which saddly won't be today

**Comment by ChirpyTurnip** [comment]
I was actually really *impressed* that you had a bug fix released *before* 2024.11 dropped. Can't say I'm surprised that people complained about it - there's always moaners. I doubt they like having it broken more. :-)

Still, I think this is a valid use case - it should be possible to publish version-dependent releases that HA "hides" until the target core version is installed. So I'm going to suggest that. :-)

**Comment by msherga** [comment]
> Message not only shows up upon installation, but also upon a reboot of HA. So likely impacting all spotcast users.

Yes can confirm I have same issue.

**Comment by fcusson** [comment]
For anyone wanting the fix now, you can do the manual install. The official release will be available tomorrow

**Comment by rvandet** [comment]
We will wait patiently and be thankfull.

**Comment by HecktorX** [comment]
I had the same issue.
ich could install spotipy adding "requirements": ["spotipy>=2.22.1"] in manifest.json. 
but now I get following error log:

Logger: homeassistant.components.websocket_api.http.connection
Quelle: custom_components/spotcast/spotcast_controller.py:278
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 22:31:26 (1 Vorkommnisse)
Zuletzt protokolliert: 22:31:26

[140587126711360] Error handling message: Unknown error (unknown_error) Jan from 192.168.3.41 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2852, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 267, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 292, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 278, in _getSpotifyConnectDeviceId
    if device["name"] == device_name:
       ~~~~~~^^^^^^^^
TypeError: 'Device' object is not subscriptable

**Comment by totow93** [comment]
> I remove the fix for `2024.11` because it was annoying to have an update you couldn't install.
can't you just change the entry in the hacs.json
`"homeassistant": "2022.3.0",` to `"homeassistant": "2024.11.0",` ?

**Comment by jaymunro** [comment]
I was wondering where that update had gone. Sure a little bothersome to have a red dot but surely more bothersome to have a non-working music system following an update. Nice work on getting it ready ahead of time.

**Comment by fcusson** [comment]
> > I remove the fix for `2024.11` because it was annoying to have an update you couldn't install.
> 
> can't you just change the entry in the hacs.json
> `"homeassistant": "2022.3.0",` to `"homeassistant": "2024.11.0",` ?
> 
> Edit: 
> That is the minimum version needed.
> https://hacs.xyz/docs/publish/start/#hacsjson

That will just be used for HACS to validate if you can install, but the install is still presented to users. Even worse there is a bug with HACS that caused older installations to be impossible to install as long as the version in the master branch was set to `2024.11.0`, even if the release has a valid minimal home assistant install.

**Comment by alvoram** [comment]
> Hi @canedje, it was requested that I remove the fix for `2024.11` because it was annoying to have an update you couldn't install. The update will come later. You can look at comments from #470 and #469.
> 
> The fix will be release once I have the time, which saddly won't be today

People are the worst sometimes. It was very clear in the notes that it was in preparation for the core update. I thought it was very impressive. Thanks for your hard work.

**Comment by rachasakr** [comment]
FYI For anyone got the same issue ATM, if you're using HACS, you may try rollback to v3.8.2:
![image](https://github.com/user-attachments/assets/c599fff5-4f12-4a36-a3f7-1154c478c99c)
![image](https://github.com/user-attachments/assets/5aab057d-6e20-4f32-97fe-941fbefc8fb6)
![image](https://github.com/user-attachments/assets/5e98cb6b-2510-475f-b122-2d9d3e24d50a)

**Comment by Ector73** [comment]
It doesn't work even when rolling back to 3.8.2.
Let's wait for 4.0!

**Comment by fcusson** [comment]
@rachasakr the only way to fix the issue is an overhaul of the device tracker to accommodate the new spotify Api library no other way around it. You can do a manual install of the current master branch to get the fix now

**Comment by SofaSurfer76** [comment]
I think we have to wait for V3.9.2 to be released again, the other day it was on the update section, but now I can find only 3.9.0 on HACS

**Comment by pathia** [comment]
@SofaSurfer76 : https://github.com/fondberg/spotcast/issues/472#issuecomment-2460738949

**Comment by fcusson** [comment]
[v4.0.0](https://github.com/fondberg/spotcast/releases/tag/v4.0.0) released

**Comment by kenlasko** [comment]
I upgraded to v4.0.0 and am still seeing the error message about missing spotipy. Running HA container 2024.11.0. Anybody else see the same thing?

**Comment by fcusson** [comment]
@kenlasko

**Comment by javiges** [comment]
> I upgraded to v4.0.0 and am still seeing the error message about missing spotipy. Running HA container 2024.11.0. Anybody else see the same thing?

+1

**Comment by DamsPer** [comment]
> I upgraded to v4.0.0 and am still seeing the error message about missing spotipy. Running HA container 2024.11.0. Anybody else see the same thing?

It's ok for me

**Comment by fcusson** [comment]
For anyone running in a container there is a [known issue](https://github.com/home-assistant/core/issues/127966) since `2024.10`. You need to add an environement variable to your container to set the PYTHONPATH  to the deps folder. You can find examples of docker-compose files [here](https://github.com/fondberg/spotcast/blob/master/container/docker-compose.stable.yaml)

**Comment by kenlasko** [comment]
Thanks @fcusson! The PYTHONPATH envvar worked a treat! Appreciate it.

**Comment by acul009** [comment]
Thanks for the patch, now I can wake up to my favourite music again :D

**Comment by diblaze** [comment]
I still get this error with 2024.11.2 and 4.0.0. 
PYTHONPATH is set, but nothing actually appears in `/config/deps`. 
I also tried setting it to `/usr/local/lib/python3.12:/config/deps`

Running with Docker container.

**Comment by Stillmatic917** [comment]
Hi I am experiencing this issue no matter what version I try.

I am running

Core
2024.12.5
Supervisor
2024.12.0
Operating System
14.1
Frontend
20241127.8

**Comment by fcusson** [comment]
@Stillmatic917 this specific issue was specific to a bug in Home Assistant Container, your message seems to indicate you are running in Home Assistant.

Please open a new ticket with all relevant information provided. This is too ambiguous to resolve in a closed ticket.
