### ISSUE TITLE
Device not found unless I make google home active

### ISSUE THREAD

**Issue by bfongbfong** [fondberg/spotcast#474]
# Bug Ticket

## Describe the bug

If I make my google home mini active by setting it as the output device in the spotify app, THEN run my start spotcast action, it works fine, but if I switch playback off of it in the spotify app and run again, the error says the device id is not found.

```
http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=3c31e63dda8e146428f7b25084e98915:
 Device not found, reason: None
```

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* I tried version 4.0.0 and got this error. After seeing the warning on the front page, I downgraded to 3.9.0 (my HA is at 2024.11), but still got the same issue
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [2024.11]
 - spotcast version: [3.9.0] and [4.0.0]

## Configuration

````yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
python_script:
shell_command:
  play_jazz_playlist: "python3 python_scripts/dinner_music2.py"
logger:
  default: info
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: SE #optional, added in 3.6.24
````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
action: spotcast.start
data:
  limit: 20
  force_playback: false
  random_song: true
  repeat: "off"
  shuffle: false
  offset: 0
  start_position: 0
  ignore_fully_played: false
  uri: spotify:playlist:6BpE8KbXneGVdlzPK3KbJr
  start_volume: 13
  spotify_device_id: 3c31e63dda8e146428f7b25084e98915
````

## Logs

* normal|debug

````log
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:387
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:27:08 PM (2 occurrences)
Last logged: 1:35:34 PM

[547559016192] Error handling message: Unknown error (unknown_error) Brandon Fong from 192.168.86.23 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 271, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play?device_id=3c31e63dda8e146428f7b25084e98915

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2852, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 343, in start_casting
    spotcast_controller.play(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 387, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 1821, in start_playback
    return self._put(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 338, in _put
    return self._internal_call("PUT", url, payload, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 293, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=3c31e63dda8e146428f7b25084e98915:
 Device not found, reason: None
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
Hi @bfongbfong that's normal, you are trying to use the spotify_id. Which means the device can only start playback if its already in your available devices. Use entity_id for chromecast devices, since we need to register it with your spotify account before we can call it with its spotify id.

**Comment by bfongbfong** [comment]
Upgrading again back to 4.0.0 and with HA 2024.11.2 worked with the entity_id. not sure it wasn't working before, thank you

**Comment by bfongbfong** [comment]
Sorry i came off a bit strong. i did check the box saying i tried entity id and it didn't work, which was true.
