### ISSUE TITLE
Configure Error

### ISSUE THREAD

**Issue by milandzuris** [fondberg/spotcast#480]
### The problem

When i want open configuration show me error

![image](https://github.com/user-attachments/assets/2adac7e3-f18c-40fa-bae0-d9b151a9b63b)

![image](https://github.com/user-attachments/assets/37db33c5-bff5-468c-8e5f-057f3b2a39a2)

### System Health details

*

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

*

### Additional information

v5.0.0-b1

**Comment by fcusson** [comment]
@milandzuris do you have any log by chance, not having this issue in my test build 

![image](https://github.com/user-attachments/assets/73c27558-6d37-4007-a330-c2b316825f15)

**Comment by milandzuris** [comment]
> @milandzuris do you have any log by chance, not having this issue in my test build
> 
> ![image](https://private-user-images.githubusercontent.com/60357894/389711068-73c27558-6d37-4007-a330-c2b316825f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NzEzNzAsIm5iZiI6MTczMjU3MTA3MCwicGF0aCI6Ii82MDM1Nzg5NC8zODk3MTEwNjgtNzNjMjc1NTgtNmQzNy00MDA3LWEzMzAtYzJiMzE2ODI1ZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDIxNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZjkzOTc2YWNhZDMyNGI3ZDcwZDg4MjQ3NDU2MWUzNTI5NmIzMzM2ZDJkMmYzM2EzYjM5ZDNhMDk3NTJjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zb83p4ZrwYJSDbF8ViVwMKV_o2ewr5og0UVJzC8g68g)

nothing

**Comment by fcusson** [comment]
ok, can you try to enable debug log

[![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=spotcast)

Just click on `enable debug logging` and then retry `configure`. That will download a file, you can drag and drop it directly in your reply

**Comment by fcusson** [comment]
I'm adding more log around that point to help find the issue, I'll push them shortly

**Comment by fcusson** [comment]
@milandzuris. Found the error. I was running on a dev container with the pre-builds for 2024.12 in which they made a change to option flows. This is an easy fix

```
Logger: aiohttp.server
Source: deps/aiohttp/web_protocol.py:477
First occurred: 7:04:56 PM (2 occurrences)
Last logged: 7:05:03 PM

Error handling request
Traceback (most recent call last):
  File "/config/deps/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 342, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/config_flow/option_flow_handler.py", line 51, in async_step_init
    options = copy_to_dict(self.config_entry.options)
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'SpotcastOptionsFlowHandler' object has no attribute 'config_entry'
```

**Comment by fcusson** [comment]
`b4` released, can confirm I am no longer able to replicate your error
