### ISSUE TITLE
Cannot find Google Speakers

### ISSUE THREAD

**Issue by PrzemekSkw** [fondberg/spotcast#498]
### The problem

Spotcast don't play music from my spotify on my google speakers. In Media Tab I see my playlists, songs, artists but nothing hapen when I choose speaker or speakers group. 
When I play on that devices from Spotify app I can only pause/play, next/previous or volume. I try different track and it don't play. When I try previous track that I play from spotify app it works.

### System Health details

```
Wersja	core-2024.12.0
Installation type	Unsupported Third Party Container
Development	false
Supervisor	false
Docker	true
Użytkownik	abc
Virtual environment	false
Python version	3.13.0
Operating system family	Linux
Operating system version	6.1.118-Unraid
CPU architecture	x86_64
Strefa czasowa	Europe/Warsaw
Configuration directory	/config
Home Assistant Community Store
error	unknown
Home Assistant Cloud
Zalogowany	false
Reach certificate server	ok
Reach authentication server	ok
Dostęp do chmury Home Assistant	ok
Dashboards
Dashboardy	5
Zasoby	67
Widoki	10
Tryb	storage
Recorder
Oldest run start time	24 listopada 2024 16:37
Current run start time	5 grudnia 2024 20:33
Estimated database size (MiB)	285.65 MiB
Database engine	sqlite
Database version	3.45.3
Spotify
Punkt końcowy Spotify API osiągalny	ok
```

### Spotcast Version

4.0.0

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

[home-assistant_spotcast_2024-12-05T19-46-45.505Z.log](https://github.com/user-attachments/files/18028803/home-assistant_spotcast_2024-12-05T19-46-45.505Z.log)

### Example YAML snippet

```yaml
configuration.yaml:

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: PL
```
secrets.yaml:
```
sp_dc: AQA5....
sp_key: 8857....
```
```


### Anything in the logs that might be useful for us?

```txt
Logs from Unraid HA docker:

2024-12-05 20:34:45.616 ERROR (SyncWorker_3) [custom_components.spotcast.spotcast_controller] Could not find device Nest Hub 2 from hass.data
2024-12-05 20:34:45.616 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'position' when rendering '{{ value_json.position }}'
2024-12-05 20:34:45.617 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01JEC5293M4FXMK0658D0JB3XX): entity_id=media_player.nesthubf857, uri=spotify:playlist:7AcLzuseeBiRF7GuwfJBpE, shuffle=False, limit=20, repeat=off, random_song=False, force_playback=False, ignore_fully_played=False, offset=0, start_volume=101>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2852, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 378, in start_casting
    raise exc
  File "/config/custom_components/spotcast/__init__.py", line 273, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
        account, spotify_device_id, device_name, entity_id
    )
  File "/config/custom_components/spotcast/spotcast_controller.py", line 296, in get_spotify_device_id
    spotify_cast_device = SpotifyCastDevice(
        self.hass,
        device_name,
        entity_id,
    )
  File "/config/custom_components/spotcast/spotcast_controller.py", line 61, in __init__
    self.castDevice = self.get_chromecast_device(device_name)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 87, in get_chromecast_device
    raise HomeAssistantError(
        "Could not find device with name {}".format(device_name)
    )
homeassistant.exceptions.HomeAssistantError: Could not find device with name Nest Hub 2
2024-12-05 20:34:54.826 ERROR (SyncWorker_1) [custom_components.spotcast.spotcast_controller] Could not find device Głośniki Google from hass.data
2024-12-05 20:34:54.826 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01JEC52QB3WFSMR8W74KYM8QDJ): entity_id=media_player.glosniki, uri=spotify:track:5humEOJehpAwMJEJmb0JJ2, shuffle=False, limit=20, repeat=off, random_song=False, force_playback=False, ignore_fully_played=False, offset=0, start_volume=101>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2852, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 378, in start_casting
    raise exc
  File "/config/custom_components/spotcast/__init__.py", line 273, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
        account, spotify_device_id, device_name, entity_id
    )
  File "/config/custom_components/spotcast/spotcast_controller.py", line 296, in get_spotify_device_id
    spotify_cast_device = SpotifyCastDevice(
        self.hass,
        device_name,
        entity_id,
    )
  File "/config/custom_components/spotcast/spotcast_controller.py", line 61, in __init__
    self.castDevice = self.get_chromecast_device(device_name)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 87, in get_chromecast_device
    raise HomeAssistantError(
        "Could not find device with name {}".format(device_name)
    )
homeassistant.exceptions.HomeAssistantError: Could not find device with name Głośniki Google
Namespaces are one honking great idea -- let's do more of those!
```
```


### Additional information

Unraid 6.12.14

**Comment by fcusson** [comment]
Hi @PrzemekSkw, thank you for the additional ticket. I have a feeling this issue might be related to the name of the speaker comprared to what is available in your cast devices.

Can you confirm if:
1. The speaker exist has a media_playey in the `cast` integration
2. That the name reported by the google home app is the exactly the same

The way we match a device with a device name is by pulling all the media_players in the cast integration and them we check the `frinedly_name` reported by the castinfo ([Relevant Code](https://github.com/fondberg/spotcast/blob/329031e6457659cb3bb477e700774abb57509b02/custom_components/spotcast/spotcast_controller.py#L74)). If your device has a slightly different name between what you typed and what castinfo report, there won't be any match.

Ideally, for chromecast device, you should simply use the entity_id, there are no risk of mismatch in these cases, otherwise, simply make sure to use exactly the same name.

**Comment by PrzemekSkw** [comment]
Hi @fcusson. Thanks for fast reply.
I know that is little mess but That names went to my HA automatically.

My Google Cast integration:
![image](https://github.com/user-attachments/assets/1b234ba7-b18c-41f8-a983-b56805f88396)

Media Tab:
![image](https://github.com/user-attachments/assets/e1fd7c66-0deb-4723-8941-2a934be67982)
Nest Hub 2 is the same as Nest Hub in Google Cast.

![image](https://github.com/user-attachments/assets/b9452be6-c466-4869-9b72-f62c3a5ac9b7)

Google Home integration:
![image](https://github.com/user-attachments/assets/aeaedd6b-8a3b-4f4d-886e-9707f1fdd969)

**Google Home App**
Nest Mini:
![Screenshot_2024-12-05-21-42-30-93_2d2bd67b5e15ae98c151ac739cd6881e](https://github.com/user-attachments/assets/4b8ba869-020e-49b2-9c55-f37752aa21ba)

Nest Hub:
![Screenshot_2024-12-05-21-42-15-80_2d2bd67b5e15ae98c151ac739cd6881e](https://github.com/user-attachments/assets/04c20a94-21cf-4505-bb22-57255c52bd77)

Group:
![Screenshot_2024-12-05-21-41-12-95_2d2bd67b5e15ae98c151ac739cd6881e](https://github.com/user-attachments/assets/055d690b-1ccb-4ec6-8009-ed51b0e2b34f)

**Comment by fcusson** [comment]
@PrzemekSkw, from what I see in your google home app, the friendly name of the device is `Głośniki`, not `Głośniki Google` Can you try that name to see if it resolves the issue?

**Comment by PrzemekSkw** [comment]
Thank You, when I go to Settings/Devices ces I see that speakers group as Głośniki 
![Screenshot_2024-12-05-22-00-45-46_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/7d54a983-e9db-468c-a8ea-aee90f396ca4)
but when I go deeper I see name as Głośniki Google. So now I change that for only Głośniki.
I will check tomorrow because my daughter is sleeping now in room with Nest Mini 😁
Don't want to wake up her.
Regards.

**Comment by PrzemekSkw** [comment]
Hi, @fcusson now when I try nothing works. My Radio Browser or DLNA Playback also stop working:
```
2024-12-06 08:45:27.665 ERROR (MainThread) [custom_components.unraid.unraid] VM list command failed with exit status 1
2024-12-06 08:46:32.289 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140144785186464] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/cast/media_player.py", line 100, in wrapper
    return_value = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/cast/media_player.py", line 558, in media_play
    media_controller.play()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pychromecast/controllers/media.py", line 630, in play
    response_handler.wait_response()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pychromecast/response_handler.py", line 54, in wait_response
    raise RequestTimeout(self._request, self._timeout)
pychromecast.error.RequestTimeout: Execution of play timed out after 10.0 s.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/media_player/__init__.py", line 827, in async_media_play
    await self.hass.async_add_executor_job(self.media_play)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
        f"{self.__class__.__name__}.{func.__name__} Failed: {err}"
    ) from err
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.media_play Failed: Execution of play timed out after 10.0 s.
```
