### ISSUE TITLE
Transferring playback error

### ISSUE THREAD

**Issue by xmow49** [fondberg/spotcast#506]
### The problem

Hello,
Thanks for the work on spotcast v5.

Sometimes, when I use `spotcast.transfer_playback` I have an error (see Anything in the logs that might be useful for us?)

This error occur only rarely; do you have any information why ? and how to avoid it ?

Thanks 

## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.62-haos-raspi
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1498
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 117.3 GB
disk_used | 33.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Mosquitto broker (6.4.1), Studio Code Server (5.18.0), Advanced SSH & Web Terminal (19.0.0), MariaDB (2.7.1), ESPHome Device Builder (2024.12.2), Network UPS Tools (0.14.0), Samba Backup (5.2.0), phpMyAdmin (0.11.0), OVH DynDNS (1.0.0), Keepalived (1.14), SomfyProtect2MQTT (2024.9.0), Portainer (dev), Silicon Labs Multiprotocol (2.4.5), ESPresense Companion (1.0.14), MQTT Explorer (browser-1.0.3), Cloudflared (5.2.4), Matter Server (6.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 27
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 décembre 2024 à 18:52
-- | --
current_recorder_run | 29 décembre 2024 à 17:53
estimated_db_size | 1349.47 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotcast</summary>

Version | 5.0.0-b19
-- | --
Oasz8tke------nzu4pqgipg68 Is Default | true
Oasz8tke------nzu4pqgipg68 Public Endpoint | ok
Oasz8tke------nzu4pqgipg68 Public Token | healthy
Oasz8tke------nzu4pqgipg68 Private Endpoint | ok
Oasz8tke------nzu4pqgipg68 Private Token | healthy
Oasz8tke------nzu4pqgipg68 Product | premium
</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_spotcast_2024-12-31T10-45-45.450Z.log](https://github.com/user-attachments/files/18280932/home-assistant_spotcast_2024-12-31T10-45-45.450Z.log)

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 743, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        variables, trigger_context, started_action
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/services/service_handler.py", line 59, in async_relay_service_call
    await handler(self.hass, call)
  File "/config/custom_components/spotcast/services/transfer_playback.py", line 63, in async_transfer_playback
    call_data = await async_rebuild_playback(call_data, account)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/services/transfer_playback.py", line 87, in async_rebuild_playback
    context_uri: str = last_playback_state["context"]["uri"]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by fcusson** [comment]
@xmow49 seems to be an edge case for when your last known active playback was context less (meaning you have no currently active playback and the last known playback cannot be resumed automatically). I'll check to push a fix, shouldn't be too complex. 

The default in this specific case should be to play your liked songs, since their is no context to resume from.

**Comment by fcusson** [comment]
@xmow49 should be fixed in build 20

**Comment by xmow49** [comment]
Hello @fcusson 
Many thanks for this quick fix.
For now, it's working, I will let you know if any other error occurs.

Thanks again and happy new year.

**Comment by fcusson** [comment]
@xmow49 glad to here it. 

Happy new year to you too

**Comment by xmow49** [comment]
Hi,
Today I have received this error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/services/service_handler.py", line 59, in async_relay_service_call
    await handler(self.hass, call)
  File "/config/custom_components/spotcast/services/transfer_playback.py", line 56, in async_transfer_playback
    "context", {}).get("uri")
                   ^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

I think is also an empty playback list.
@fcusson Do you know the timeout of an active playback on Spotify?
Can it be related to a certain amount of time of non playing music?

Thanks

**Comment by fcusson** [comment]
@xmow49 that's my bad, I wrongly made the assumption that the key `context` was missing from the playback state but in reality, the key exist, but return `null`. That's a quick fix.

> Can it be related to a certain amount of time of non playing music?

I'm already taking into account the expiration of the playback context, that's actually while trying to rebuild the context from the last known state that you are getting this error. Just tweaked the function a bit, should work better now. I also modified the tests to better account for the real format of a context less playback state.

**Comment by fcusson** [comment]
just pushed build 21, should be working fine now

**Comment by xmow49** [comment]
Thanks again for your responsiveness.
I'll keep you informed of any further errors.

**Comment by fcusson** [comment]
Issue inactive for 3 weeks. I'll close it for the moment. Please reopen if needed
