### ISSUE TITLE
One of four chromecast devices does not work

### ISSUE THREAD

**Issue by kiwikern** [fondberg/spotcast#65]
Spotcast: v2.8.0
Home Assistant: v0.106.5

I have one chromecast and three Google Home devices. All are integrated with my HA, e.g. playing voice commands for all four of them works fine. Somehow, running spotcast does not work only for entity `media_player.googlehome9038`; however, the exact same service call does work perfectly e.g. for entity `media_player.googlehome3459`.

When I run `spotcast.start` with this service data I receive the following stack trace:

service data:
```
entity_id: media_player.googlehome9038
uri: 'spotify:playlist:...'
```

Home Assistant Logs:
```
2020-03-08 02:30:25 ERROR (MainThread) [custom_components.spotcast] Could not find device Bad from hass.data, falling back to pychromecast scan
2020-03-08 02:30:33 INFO (MainThread) [pychromecast] Querying device status
2020-03-08 02:30:33 INFO (MainThread) [pychromecast] Querying device status
2020-03-08 02:30:33 INFO (MainThread) [pychromecast] Querying device status
2020-03-08 02:30:33 INFO (MainThread) [pychromecast] Querying device status
2020-03-08 02:30:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1838148368] Could not find device with name Bad
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 182, in start_casting
    spotify_cast_device = SpotifyCastDevice(hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID))
  File "/config/custom_components/spotcast/__init__.py", line 237, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 263, in getChromecastDevice
    raise HomeAssistantError('Could not find device with name {}'.format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Bad
```

With the other entities, the playlist starts playing and I find the following log messages:
```
2020-03-08 02:36:27 INFO (MainThread) [pychromecast] Querying device status
2020-03-08 02:36:27 INFO (Thread-11) [pychromecast.controllers] Receiver:Launching app CC32E753
```

What could be the reason for it to fail?

**Comment by kiwikern** [comment]
The overwritten entity name in HA differed from the name of the Google Home device.
