### ISSUE TITLE
No device with id "" known by Spotify and Failed to get device id from Spotify

### ISSUE THREAD

**Issue by heqirong** [fondberg/spotcast#68]
Logger: custom_components.spotcast
Source: custom_components/spotcast/__init__.py:184
First occurred: 下午11:16:32 (2 occurrences)
Last logged: 下午11:16:32

No device with id "7260b349a0fc9f487fc190c7941466da" known by Spotify
Known devices: []

Logger: homeassistant.components.websocket_api.http.connection.140124176598800
Source: custom_components/spotcast/__init__.py:291
Integration: websocket_api (documentation, issues)
First occurred: 下午11:19:13 (1 occurrences)
Last logged: 下午11:19:13

Failed to get device id from Spotify
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 184, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 291, in getSpotifyDeviceId
    raise HomeAssistantError('Failed to get device id from Spotify')
homeassistant.exceptions.HomeAssistantError: Failed to get device id from Spotify

**Comment by nrgbistro** [comment]
I am getting a similar error message, not sure if it's related. I am calling spotcast from `Mini Media Player` and my error message is: `Failed to called Spotcast/start: could not find device with name 'Downstairs'`. In my HA devices list, I have a device called 'downstairs' (This is a collection of Amazon echos linked together from the alexa app). Would this affect Spotcast working?

**Comment by sermayoral** [comment]
Same here:

```
uri: spotify:playlist:1gtrESi2ZEgPE8hEMd9Oka
entity_id: media_player.gh_servicio
```

It detects the friendly name of the entity, but i get this error and it does not work :-(

```
20-03-27 14:36:08 DEBUG (MainThread) [custom_components.spotcast] cast info: None
2020-03-27 14:36:08 ERROR (MainThread) [custom_components.spotcast] Could not find device Google Home Mini Servicio from hass.data, falling back to pychromecast scan
2020-03-27 14:36:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1870603568] Could not find device with name Google Home Mini Servicio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 182, in start_casting
    spotify_cast_device = SpotifyCastDevice(hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID))
  File "/config/custom_components/spotcast/__init__.py", line 237, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 263, in getChromecastDevice
    raise HomeAssistantError('Could not find device with name {}'.format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Google Home Mini Servicio
```

**Comment by fondberg** [comment]
This is not a spotcast issue. Please use device_name instead of entity_id, seems HA has meesed the mapping up

**Comment by peceq** [comment]
> This is not a spotcast issue. Please use device_name instead of entity_id, seems HA has meesed the mapping up

i tried  change entity_id to device_name and spotify_device_name but still the same ....

![image](https://user-images.githubusercontent.com/26087628/112126065-5de3e780-8bc4-11eb-869a-54345fbd61a4.png)

**Comment by read1st** [comment]
> > This is not a spotcast issue. Please use device_name instead of entity_id, seems HA has meesed the mapping up
> 
> i tried change entity_id to device_name and spotify_device_name but still the same ....
> 
> ![image](https://user-images.githubusercontent.com/26087628/112126065-5de3e780-8bc4-11eb-869a-54345fbd61a4.png)

same here!

**Comment by ludwigvdb** [comment]
Same here since yesterday.

**Comment by mcfly2283-ai** [comment]
same here, maybe also since yesterday... Nothing was changed. sp/dc Key changed, same Problem

**Comment by sermayoral** [comment]
Same here, since yesterday:

`
Logger: homeassistant.core
Source: custom_components/spotcast/__init__.py:478
First occurred: 16:35:23 (1 occurrences)
Last logged: 16:35:23
Error executing service: <ServiceCall spotcast.start (c:b9934d0e6b15dbcc7c62c4fde3f89168): device_name=Cocina, uri=spotify:playlist:2zMHcb4y0hT82xARlWkV4y, repeat=context, random_song=True, shuffle=True, offset=0, start_volume=101, force_playback=False>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1504, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 296, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 478, in getSpotifyDeviceId
    raise HomeAssistantError("Failed to get device id from Spotify")
homeassistant.exceptions.HomeAssistantError: Failed to get device id from Spotify
`

**Comment by sermayoral** [comment]
This thread is closed. Same behaviour as https://github.com/fondberg/spotcast/issues/170
