### ISSUE TITLE
Not able to use spotify artist URIs for spotcast.start service

### ISSUE THREAD

**Issue by calebmah** [fondberg/spotcast#69]
Tried to use an artist URI (eg. `spotify:artist:abcde....xyz`) in the start service but returned a 400 error:

```
http status: 400, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=redacted:
 Can't have offset for context type: ARTIST
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 137, in _internal_call
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/me/player/play?device_id=redacted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 196, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 119, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 1057, in start_playback
    "me/player/play", device_id), payload=data)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 207, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 145, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=redacted:
 Can't have offset for context type: ARTIST
```

Is it possible to fix the request to enable using of artist URIs?

**Comment by fondberg** [comment]
I have very little time in these corona times for enhancements but maybe someone can help and and create a PR seeing as this is open source and totally free

**Comment by fondberg** [comment]
Hmmm, I tested an artist URI with the web api console and I couldn't get it to work.
https://developer.spotify.com/console/put-play/
Does it work for you? If not I think artist URI:s are not supported in the web api

**Comment by fondberg** [comment]
oh, wait. I think I know what was wrong. I think I can fix it

**Comment by fondberg** [comment]
Fixed in https://github.com/fondberg/spotcast/releases/tag/v2.9.0
