### ISSUE TITLE
Could not find device with name ...

### ISSUE THREAD

**Issue by sermayoral** [fondberg/spotcast#70]
Anybody know why I can't send a playlist to my Google Home? I use this service:
```
uri: spotify:playlist:1gtrESi2ZEgPE8hEMd9Oka
entity_id: media_player.gh_servicio
```
It detects the friendly name of the entity, but i get this error and it does not work :-(
```
20-03-27 14:36:08 DEBUG (MainThread) [custom_components.spotcast] cast info: None
2020-03-27 14:36:08 ERROR (MainThread) [custom_components.spotcast] Could not find device Google Home Mini Servicio from hass.data, falling back to pychromecast scan
2020-03-27 14:36:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1870603568] Could not find device with name Google Home Mini Servicio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 182, in start_casting
    spotify_cast_device = SpotifyCastDevice(hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID))
  File "/config/custom_components/spotcast/__init__.py", line 237, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 263, in getChromecastDevice
    raise HomeAssistantError('Could not find device with name {}'.format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Google Home Mini Servicio
```
TTS from Home Assistant works good, but i cannot get this working. Thanks and sorry for disturbances :-(

**Comment by fondberg** [comment]
Mapping seems to be broken between device_name and entity_id. Please try with device_name instead of entity_id

**Comment by sermayoral** [comment]
@fondberg thanks.

It works with device_name, but using Google Home name, not Home Assistant friendly name. That was the problem:

- entity_id: media_player.gh_kitchen
- friendly_name: Google Home Kitchen
- device_name: Kitchen

spotcast get HA friendly_name (Google Home Kitchen) but doing chromecast by this name, it does not find anything, so i get this error.

Thanks!!

**Comment by fondberg** [comment]
If you find the reason for it being mapped wrong, please tell me so I can put in a fix (or remove entity_id as it seems buggy)

**Comment by sermayoral** [comment]
Thanks @fondberg 

I know the problem, but i don't see a solution of this in your side, because Home Assistant does not save the device name.

I think the only solution to this is using device name as friendly name in Home Assistant. In that way everything works fine

**Comment by fondberg** [comment]
Best is to rename the actual chromecast device which will then be renamed in HA automatically

**Comment by zaitochi** [comment]
I have the same thing, but it was working before.

**Comment by stefancvetkovic** [comment]
This starts to pissed me off. Everything works for weeks/months, and suddenly, `Could not find device Denon AVR-X2400H from hass.data`

**Comment by micheledm** [comment]
Same here, 10-ish days ago started doing the same without touching anything

**Comment by fondberg** [comment]
Try new release and if open source pisses you off @stefancvetkovic  you should either help out and fix things or stop using it. People are putting their precious spare time into sharing things for FREE

**Comment by stefancvetkovic** [comment]
I thought that if I report a problem, I'm helping a little bit..
But yes, and you are absolutely right! I will definitely stop using it.
Cheers.

**Comment by fcusson** [comment]
closing due to inactivity, please reopen if required
