### ISSUE TITLE
extra keys not allowed @ data['transfer_playback']

### ISSUE THREAD

**Issue by nelbs** [fondberg/spotcast#73]
Hi,

I configured the spotify component, and installed spotcast and the custom spotify card. The connection with spotify works. However if I choose a mediaplayer (within the spotify card) from the list of chromecast devices I get the following error message and log.

![image](https://user-images.githubusercontent.com/6464671/77887863-9a0f9100-726b-11ea-97fb-5167e24b668e.png)

```
2020-03-30 09:40:31 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1545439056] extra keys not allowed @ data['transfer_playback']
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1212, in async_call
    processed_data = handler.schema(service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['transfer_playback']
```

**Comment by kleinc80** [comment]
Hi @nelbs ,

The parameter transfer_playback does not exist anymore, that's why you get "extra keys not allowed" if you still have it in your config. That's a change in v2.9 compared to v2.8.

Just remove it, and it should be fine. You might want to have a look at the new parameter force_playback.

Best
 Chris

**Comment by nelbs** [comment]
Thanks, now i see @fondberg will change the spotify card. 

https://github.com/custom-cards/spotify-card/issues/56#issuecomment-605875670
