### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by MyAccount-dot** [fondberg/spotcast#91]
Hello everyone,
I installed spotcast to work with the custom spotify card but I'm struck with a "Exceeded 30 redirects" error. The spotify card loads and authenticates smoothly, it quickly detects all of my speakers but when I select any of them I get a failed call to spotcast/start: exeeded 30 redirects.

Is there anything I am doing wrong?

Thanks
 (traceback below)
---

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1292, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 166, in start_casting
    access_token, expires = get_spotify_token(sp_dc=dc, sp_key=key)
  File "/config/custom_components/spotcast/__init__.py", line 85, in get_spotify_token
    data = st.start_session(sp_dc, sp_key)
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 19, in start_session
    headers=headers, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by jacobswe** [comment]
I had this same error, it turned out I had only copied a portion of the sp_key and was able to authenticate but not initiate the playing. Can you generate some new keys to try?

**Comment by MyAccount-dot** [comment]
And you are in fact correct! Thank you so much, you saved me a LOT of time...



> I had this same error, it turned out I had only copied a portion of the sp_key and was able to authenticate but not initiate the playing. Can you generate some new keys to try?
