### ISSUE TITLE
TimeoutError in AppDaemon

### ISSUE THREAD

**Issue by provinzio** [fondberg/spotcast#94]
I use the service `spotcast.start` in my AppDaemon alarm clock.

Since the service takes some time (>10sec) and does not return any results early, AppDaemon throws a timeout error, even though the service gets executed correctly.

My current solution is to except the possible timeout errors and ignore it.

```
try:
    self.call_service(
        "spotcast/start",
        entity_id="media_player.uberall",
        uri="spotify:playlist:1F60OIQoIgpXCrKJny7C8z"
    )
except (concurrent.futures._base.TimeoutError, asyncio.exceptions.TimeoutError):
    pass
```

**Edit:**
But this does not work always apparently.
I found this in my logs.

```
2020-06-06 15:23:20 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:524fbd2e9196417f8237856ec24354f1): entity_id=media_player.uberall, uri=spotify:playlist:3roeMsWrNcImq6wGBJb4j8, shuffle=True, offset=0, random_song=False, force_playback=False, repeat=off>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1292, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 178, in start_casting
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/__init__.py", line 267, in startSpotifyController
    sp.launch_app()
  File "/usr/local/lib/python3.7/site-packages/pychromecast/controllers/spotify.py", line 85, in launch_app
    "Timeout when waiting for status response from Spotify app"
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```

Starting the service from the UI does work always.
The errors seem to appear only in combination with AppDaemon.

**Comment by notpurum** [comment]
I dont have the AppDaemon but still get the same error

**Comment by fondberg** [comment]
As spotipy is synchronous uou need to wrap your own async if you need it.

Does it work fast when using the UI?

**Comment by provinzio** [comment]
Oh dear.. I started the service from my app. Nothing happend. I thought I misspelled the uri, but it seems I haven't. 2 hours later the requested playlist started. 
```
2020-06-07 16:54:38 INFO (SyncWorker_10) [pychromecast] Querying device status
2020-06-07 16:54:38 ERROR (Thread-11) [pychromecast.socket_client] [(192.168.178.21):42595] Failed to connect, retrying in 5.0s
2020-06-07 16:54:40 INFO (SyncWorker_4) [pychromecast] Querying device status
2020-06-07 16:54:40 ERROR (Thread-12) [pychromecast.socket_client] [(192.168.178.21):42595] Failed to connect, retrying in 5.0s
2020-06-07 16:59:18 WARNING (Thread-10) [pychromecast.socket_client] [Casty McCastface(192.168.178.29):8010] Heartbeat timeout, resetting connection
2020-06-07 16:59:37 ERROR (Thread-10) [pychromecast.socket_client] [Casty McCastface(192.168.178.29):8010] Failed to connect to service Casty McCastface._googlecast._tcp.local., retrying in 5.0s
2020-06-07 17:17:08 INFO (SyncWorker_10) [pychromecast.controllers] Receiver:Launching app CC32E753
2020-06-07 17:17:09 INFO (SyncWorker_4) [pychromecast.controllers] Not launching app CC32E753 - already running
2020-06-07 17:17:10 ERROR (SyncWorker_10) [spotipy.client] HTTP Error for PUT to https://api.spotify.com/v1/me/player/play?device_id=80cb9769d3cbe503ffca1b4d575f59b3 returned 400 due to Invalid context uri
2020-06-07 17:17:10 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:cad06cafd8774919811345928f17080e): entity_id=media_player.uberall, uri=otify:playlist:3ehf3A4sCNIAdgOgpvKQ3B, force_playback=False, shuffle=False, offset=0, repeat=off, random_song=False>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 172, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/me/player/play?device_id=80cb9769d3cbe503ffca1b4d575f59b3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1269, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1292, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 120, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 1326, in start_playback
    self._append_device_id("me/player/play", device_id), payload=data
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 222, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 187, in _internal_call
    headers=response.headers,
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=80cb9769d3cbe503ffca1b4d575f59b3:
 Invalid context uri
2020-06-07 17:17:10 ERROR (Thread-9) [pychromecast.socket_client] [Überall(192.168.178.22):42595] Error reading from socket.
2020-06-07 17:17:10 WARNING (Thread-9) [pychromecast.socket_client] [Überall(192.168.178.22):42595] Error communicating with socket, resetting connection
2020-06-07 17:17:13 INFO (Thread-9) [pychromecast.socket_client] [Überall(192.168.178.21):42595] Connection reestablished!
2020-06-07 17:17:32 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1798529168] Connection closed by client
2020-06-07 17:22:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-06-07 17:22:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

**Comment by fondberg** [comment]
The issue seems to be with your URI.

Invalid context uri

**Comment by provinzio** [comment]
NVM you are right, I had a typo in there 
 `uri=otify:playlist:3ehf3A4sCNIAdgOgpvKQ3B`. But I don't understand why it started randomly after one hour. 

I tested the service again on my notebook in the ui and it worked just fine. It does have a delay but it's ok for my purpose.

I guess I have to look for an async Version myself or at least an bigfix. I hate to play radio in the morning. :D

Anyway, thanks for your clarification.

**Comment by provinzio** [comment]
I tried to call the service today again and it takes ~ 40sec to start music on my device.

The core log does not list something odd.
```
2020-06-09 11:42:48 INFO (SyncWorker_8) [pychromecast] Querying device status
2020-06-09 11:42:48 INFO (SyncWorker_8) [pychromecast.controllers] Receiver:Launching app CC32E753
```

Starting spotify music from voice command or smartphone spotify app runs normal (~5sec).

Any suggestions?

**Comment by fondberg** [comment]
I think this might be caused by issues in pychromecast and zeroconf. There are some fixes done so please test again after the new release I'm doing today which requires 0.111 of HA

**Comment by fondberg** [comment]
Try the new release (requires HA 0.111)

**Comment by provinzio** [comment]
Updated to HA0.111 and spotcast v3.1, but it takes ~40 sec to start `spotcast.start` after all.

And I am not sure whether the long boot up time has to do something with spotcast (also see #93). The long boot time has not changed after the update. (~5-10min i guess, i never measured it accuretly).
```2020-06-11 10:47:19 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.```

**Comment by provinzio** [comment]
I did some debugging steps:

I started by removing spotcast and spotify integration.

- Boot time: <1min

Fresh install spotcast with HACS and readd config to configuration.yaml
```
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
```

- Boot time: ~10min
- No specific core log entries besides `Setup of default_config is taking over 10 seconds`
- Music startup time after service start from ui: 45sec


I use a Raspberry Pi 3B with Raspbian and supervised Hassio.


Is there a way to look at integrations logs like with addons?

**Comment by fondberg** [comment]
I'm sorry but I can't think of anything that can help you with the time to get the token.

regarding the long boot times; I think you have some dependency problem.
Try removing spotcast using HACS and then make sure it is gone from custom_components.
Reboot your entire PI.

Now install spotcast again and restart.
