### ISSUE TITLE
Incompatibility with HASS 0.111.0

### ISSUE THREAD

**Issue by syphernl** [fondberg/spotcast#96]
After upgrading to HASS 0.111.0 my Google Cast devices all became "unavailable". 
The HASS logs showed a traceback regarding pychromecast:  
```
2020-06-10 17:16:42 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/cast/discovery.py", line 87, in setup_internal_discovery
    listener = pychromecast.CastListener(
AttributeError: module 'pychromecast' has no attribute 'CastListener'
```

I reported this as https://github.com/home-assistant/core/issues/36631 however it seems that Spotcast _might_ be causing this. 
After commenting out the spotcast configuration and restarting HASS my Cast devices properly show up. Re-enabling the Spotcast configuration entry and restarting HASS immediately results in all cast devices from being unavailable.

**Comment by fondberg** [comment]
Try the new release (requires HA 0.111)

**Comment by HITChris** [comment]
Fixed - thanks.
